### ISSUE TITLE
Query to fetch external datasets is very slow

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#1010]
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

No - This is a new bug

### Version

1.6.1

### Describe the bug

After loading some external profiles into Aerie in prep for our thread test in July, the query to fetch external datasets takes nearly a minute to return. When multiple users (~4) were viewing the same plan the query took nearly 8 min to return. To the user it appears that the data is not available.

Query in question:
```
{
    "query": "#graphql\n    query GetProfilesExternal($planId: Int!) {\n      plan_dataset(where: { plan_id: { _eq: $planId } }) {\n        dataset {\n          profiles {\n            dataset_id\n            duration\n            id\n            name\n            profile_segments(order_by: { start_offset: asc }) {\n              dataset_id\n              dynamics\n              is_gap\n              profile_id\n              start_offset\n            }\n            type\n          }\n        }\n        offset_from_plan_start\n      }\n    }\n  ",
    "variables": {
        "planId": 8
    }
}
```

For the July thread test we will need to work with what we have, but long term this data needs to load faster.

### Reproduction

Observable on our ops venue. Contact me for details.

### System Info

```shell
MacOS Chrome
```

### Severity

Moderate

**Comment by mattdailis** [comment]
This was addressed by https://github.com/NASA-AMMOS/aerie/pull/992
