### ISSUE TITLE
Configurable spice and merlin_file_store directory

### ISSUE THREAD

**Issue by achong1024** [NASA-AMMOS/aerie#1022]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Aerie services, by default, will goto `/usr/src/spice` to find the spice files and `/usr/src/app/merlin_file_store or /app/files` for the adaptation files.  Issues occur when we deploy Aerie services to the Cloud, which currently only support one efs mounting point.  We have to modify each service requiring two volumes of mounting points with a symlink.

e.g.
our mounting point is mount to `/usr/src/app/merlin_file_store`, hence we have to make a symlink
/`user/src/app/merlin_file_store/spice` to `/usr/src/spice`
docker exec -d aerie_merlin ln -sfn /usr/src/app/merlin_file_store/spice /usr/src/spice

### Describe the feature request

I want to be able to specified the spice kernel path, and all volumes paths.  That will allow me to have a cleaner setup on the efs, and not require me to build a custom image for every delivery.

e.g.
I can have a mounting point at `/usr/src/aerie`
and I can change the spice kernel path to `/usr/src/aerie/spice` and adaptation files path to `/usr/src/aerie/merlin_file_store`

Something like below will be great
    spiceDir = os.environ['SPICE_DIRECTORY'] if 'SPICE_DIRECTORY' in os.environ else '/usr/src/spice'

**Comment by achong1024** [comment]
Update: turns out the change for the `spice kernel path` is in the Clipper model.  Thanks to Theresa Kamerman, she already have a PR to fix that on our end

**Comment by mattdailis** [comment]
Sounds like this issue has been resolved. Please re-open if I am mistaken.
