### ISSUE TITLE
Unify how MissionModelIds are parsed in Scheduler and Merlin Bindings

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#1063]
In the Scheduler, `MissionModelIds` are parsed using `missionModelP`, which is a wrapper around a `longP`. In Merlin, `MissionModelIds` are parsed as Strings. Additionally, the Hasura Actions use the ID type for MissionModelIds rather than Int. Merlin needs to be updated to match how the Scheduler handles MissionModelIds.

**Comment by camargo** [comment]
Related to https://github.com/NASA-AMMOS/aerie/issues/519
