### ISSUE TITLE
Allow scheduling goals to reference external profiles

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#1071]
- Scheduling goals should be able to reference external profiles
- Just include external datasets associated with plans, not simulation datasets
- Slack thread: https://jpl.slack.com/archives/CJ07FGRPH/p1692721764155499

Use case:
-  Mission uploads pre-computed geometric profiles once per plan (mostly static data), and they want scheduling goals to reference those external profiles to schedule against.
```[tasklist]
### Tasks
- [ ] Generate typescript types for external profiles similarly to what's done for constraints
- [ ] Load external profiles before scheduling (only if associated to plan or up-to-date simulation results)
```

**Comment by adrienmaillard** [comment]
Realizing that constraints will work out of the box if the external profile are loaded in the `Environment` as in constraint processing.

**Comment by adrienmaillard** [comment]
Referencing the slack discussion https://jpl.slack.com/archives/CJ07FGRPH/p1692721764155499
