### ISSUE TITLE
Stream simulation results into the database

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#1096]

**Comment by Mythicaeda** [comment]
[Excalidraw link](https://excalidraw.com/#room=4d39daf1c3ae97077256,sTk9Nliof5KKeU5ffdES6w) from [design thread](https://jpl.slack.com/archives/CJ07FGRPH/p1712951947360269).

**Comment by Mythicaeda** [comment]
Our goal with this was to improve peak memory usage for large mission models. Simulation run time is not expected to change much, but a [follow-up ticket to improve it has been opened](https://github.com/NASA-AMMOS/aerie/issues/1516). Scheduling runtime is not anticipated to change at all.

You can [check the PR](#1507) for an in-depth comparison of memory usage made using the Europa Clipper Model.

For a better sense of impact, however, I performed a memory comparison between `develop` and `streaming` using a variant of Endurance's mission model that did not include power modelling. Of note:

- **Heap Size**: Streaming peaked at a heap size of 5GB while writing Simulation Results but generally was at 3-4GB, while Develop peaked at 6.5 GB but was generally at about 5 GB during that time.
- **Non-Heap Memory**: Streaming had a very level non-heap memory usage while Develop had an increase in non-heap memory usage around when Simulation Results were being processed. Streaming peaked at 42MB but generally used 39MB, while Develop peaked at 45MB, but generally used 35MB (pre-minute 7)  to 42MB (post-minute 7).
- The peak number of objects allocated in Streaming was 12 million, while the peak number of objects allocated on develop was 14 million.
- Streaming took 14 minutes to complete while Develop took 12 minutes.

Below are three screenshot’s showing the comparison for 1) heap 2) non heap and 3) recorded objects. Develop is shown on the left and Streaming is shown on the right. Please be aware in (2) that the vertical scale differs for the two graphs.

<img width="1493" alt="heap comparison" src="https://github.com/user-attachments/assets/77a8152d-9c63-4ecd-a6f8-f0cfb1bf160e">
<img width="1509" alt="non-heap comparison" src="https://github.com/user-attachments/assets/f82f9e58-3b35-4c89-9371-6a5289921b82">
<img width="1509" alt="recorded object comparison" src="https://github.com/user-attachments/assets/a9370aa3-624d-4872-9f99-1c5f1ccea522">
