### ISSUE TITLE
Add Support for SSO with CAM

### ISSUE THREAD

**Issue by achong1024** [NASA-AMMOS/aerie#1100]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

The introduced JWT with our Cloud deployment required users to sign in twice—one at the CAM log-in page (the reverse proxy) and one at the Aerie UI.  

### Describe the feature request

Clipper uses CAM as the authentication method for our Aerie Deployment.   A more integrated way will be preferred, and a proper handshake between CAM and the Gateway is needed.  I included a Figma flow diagram link and the screen shoot to illustrate the idea better.  

Some ideas:
UI can have a new env_variable to enable "third-party" authentication that passes the request to the gateway.  
JWT renewal/refresh happens automatically using the valid CAM token (Invalid CAM token will be redirected to the user to the CAM log-in page)

Figma Link
https://www.figma.com/file/0o5hZAkIQDVCcuesKoLseg/SSO?type=whiteboard&node-id=0%3A1&t=JmuRb2KL3RYcFJ5S-1

![SSO](https://github.com/NASA-AMMOS/aerie/assets/130383906/955fd6d7-e08d-4299-9f4d-ebdeae924112)

**Comment by cartermak** [comment]
Ideally, the mechanism by which the client passes a CAM token to the Gateway would be a simple request that we could easily replicate for our tools that interact via the API. I'll suggest that this functionality could be built into the `/auth/user` and/or `/auth/session` endpoints s.t., if a CAM token is passed in a cookie to one of these endpoints, the Gateway just returns the JWT. Alternatively, it could be a different endpoint dedicated to authenticating via a token in a cookie.
