### ISSUE TITLE
Return Compilation Errors When Constraints Fail to Compile

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#1117]
When running Constraints, if a constraint has errors that prevent it from compiling, the Merlin Server does not include these errors in its response. This means that the only way to see what the error was is to open the container's Docker log and look for the exception. These errors should instead be parsed and returned as part of the response payload.

**Comment by parkerabercrombie** [comment]
I ran into this again yesterday; would be great to get this fixed. The most common source of error (at least for me) is referencing a resource that does not exist.

**Comment by mattdailis** [comment]
May help shed light on #1208
