### ISSUE TITLE
Evaluate using an Aerie sequencing DSL

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#1120]
- How long would it take to implement the entire Seq JSON spec?
- Maintainability?
- How easy is it to design the sequencing DSL?
- Others?

https://github.com/NASA-AMMOS/aerie-sequence-editor

**Comment by dandelany** [comment]
@goetzrrGit has been reviewing this as a possibility - we need to discuss with @joswig and @delany after @goetzrrGit writes up some details on this ticket. Thanks!

**Comment by goetzrrGit** [comment]
Here is my writeup. 

https://github.com/NASA-AMMOS/aerie/discussions/1148

**Comment by joswig** [comment]
Implemented Phoenix Editor
