### ISSUE TITLE
Add JWT Expired check to `/auth/session` endpoint

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#1127]
The `/auth/session` endpoint in the Gateway is used to validate if a user's session is still valid. As part of this, it ought to check that the JWT isn't expired.

**Comment by camargo** [comment]
I investigated this and found the `/auth/session` endpoint already verifies the JWT via the [decodeJwt function call](https://github.com/NASA-AMMOS/aerie-gateway/blob/e4bfc45daec4d568f5bbb8fc723cf32cdf8f33d7/src/packages/auth/functions.ts#L218). If you use an expired JWT the endpoint returns a `No JWT payload found` error. The Gateway logs show a `TokenExpiredError: jwt expired` error. I'm going to open a PR to report the expired JWT error to the caller: https://github.com/NASA-AMMOS/aerie-gateway/pull/42
