### ISSUE TITLE
Validate that RequestedRole is an AllowedRole in ChangeRole endpoint

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#1129]
Example user session (simplified, decoded):
```json
{
    "activeRole": "viewer",
    "defaultRole": "aerie_admin",
    "allowedRoles": ["viewer", "aerie_admin"]
}
```
Example request to `/auth/changeRole`:
```json
{
  "role": "user"
}
```

Expected behavior: Failure message (ie `'user' is not in 'allowedRoles'`)
Current behavior: Success message (`Role changed successfully`), `activeRole` is incorrectly set to `aerie_admin`

This bug occurs because the value of `role` in the request isn't validated by the `changeRole` function in the Gateway.

**Comment by camargo** [comment]
Per @mattdailis We should also revisit the change role endpoint to see if it's needed. Look into storing the active role somewhere in the browser.

**Comment by camargo** [comment]
Noting [here is the logic that does this](https://github.com/NASA-AMMOS/aerie-gateway/blob/673ad17348dfdf6297043bedcd4cba1638655939/src/packages/auth/functions.ts#L105). We just set to the default role if the requested role is not allowed. We should instead just not change the role, and show a failure.

That said, we should first see about just removing the change role functionality from the Gateway all together.
