### ISSUE TITLE
Log simulation progress and elapsed time

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#1131]
### Checked for duplicates

No - I haven't checked

### Alternatives considered

Yes - and alternatives don't suffice

### Describe the feature request

It would be useful to see simulation progress and total elapsed time output in the Aerie worker log (maybe enabled by a log level environment variable). It would be especially useful to have some indication when Aerie starts writing results to the database and when it is finished writing, as saving to the database can be a big chunk of total simulation time in our tests.

**Comment by mattdailis** [comment]
Closing as completed as of Aerie 1.14.0
