### ISSUE TITLE
Schema Mismatch Between Cached Constraint Run and Action Response

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#1150]
The cached results in the `constraint_run` table stores the names of the used resources under "resourceNames". The response from the Constraints action stores them under "resourceIds"

Additionally in the `violations`part of results, the violating windows are stored as `windows` in the action response and as `violationWindows` in the cached results

Also, `type` in the response vs `constraintType` in the cache

**Comment by mattdailis** [comment]
If `constraint_run` should not be queried directly, consider hiding it from the hasura schema
