### ISSUE TITLE
Aerie CAM deployment

### ISSUE THREAD

**Issue by mattdailis** [NASA-AMMOS/aerie#1164]
In addition to our development deployment, it would be useful to standup a "staging" aerie deployment (e.g. `aerie-staging.jpl.nasa.gov`), that runs the latest released version of Aerie, and uses HTTPS and CAM, like a production deployment of Aerie would.

**Comment by joswig** [comment]
Alvin highlighted some details on #1100 and we may want to merge these issues

**Comment by dandelany** [comment]
We've deployed a demo production Aerie environment at https://aerie-prod.jpl.nasa.gov

Future work + documentation for SSO deployments will be covered in #1100
