### ISSUE TITLE
Upgrade to JRE 21

### ISSUE THREAD

**Issue by skovati** [NASA-AMMOS/aerie#1209]
Temurin has officially released JRE 21 builds. In addition to lots of fun new features (pattern matching improvements, green threads), the current JRE 19 is EOL and no longer receiving security updates. JRE 21 is also an LTS release.

https://adoptium.net/temurin/releases/?os=linux&package=jre

**Comment by dandelany** [comment]
This is nearly done (#1237) but requires a bit more discussion with @mattdailis since it enables new threading features in JRE 21, to ensure there are no unexpected breaking changes.

**Comment by dandelany** [comment]
@skovati here are some other places which may need to be updated to `21`:
* [ ] [aerie DEVELOPER.md setup docs](https://github.com/NASA-AMMOS/aerie/blob/develop/docs/DEVELOPER.md#prerequisite-software)
* [ ] [aerie-mission-model-template](https://github.com/search?q=repo%3ANASA-AMMOS%2Faerie-mission-model-template%2019&type=code)
* [ ] Other WIP models from Starter Models Working Group, eg. [aerie-simple-model-power](https://github.com/NASA-AMMOS/aerie-simple-model-power#prerequisites)?

In general, is this a breaking change that will require updating/rebuilding a mission model to work with the new version, or will older mission model `JAR`s still work?

**Comment by skovati** [comment]
Copying my comment on the PR to this issue:

Manual testing has shown:

    JDK 19 built models run fine on Aerie w/ JRE 19
    JDK 19 built models run fine on Aerie w/ JRE 21
    JDK 21 built models DO NOT run on Aerie w/ JRE 19
    JDK 21 built models run fine on Aerie w/ JRE 21

So, upgrading the JRE of `aerie-*` container images should be backwards compatible, but mission modelers will need to hold off on upgrading to JDK 21 until their target venues are also running JRE 21.
