### ISSUE TITLE
Activities with controllable duration are not usable if their value mapper is custom

### ISSUE THREAD

**Issue by adrienmaillard** [NASA-AMMOS/aerie#1220]
Interesting issue that has not blown up yet because Clipper does not actively use `ControllableDuration` yet but that we see on the external scheduler side. When we have such a parameter that controls the duration, we know that on the model side, it is represented by a `Duration` object. We assumed that the value mapper would our own but actually we don’t know what value mapper the mission model uses. Clipper uses another value mapper. The problem is that we need to be able to serialize/deserialize this parameter. The mappers are well hidden in the mission model and depend on a naming convention/code generation.

One path forward is to provide the value mapper in `DurationType.Controllable`. Problem, `ValueMapper` is in 1) merlin-framework and `DurationType` in 2) merlin-sdk and there is a dependency 1 ->2 but we need the opposite.

Other solution would be to rely on generated code in a similar fashion as `DurationType.ParametricDuration` and generate a new class that would call the value mapper of the controllable duration.

**Comment by mattdailis** [comment]
Copying from a slack conversation, for tracking purposes:

> The mission model needs to provide the scheduler a way to serialize and deserialize durations. It doesn't have to literally be a "ValueMapper" - it can simply be two methods SerializedValue serializeDuration(Duration duration) and Duration deserializeDuration(SerializedValue serializedValue). The `SchedulerModel` interface is a natural place to add these methods
