### ISSUE TITLE
Support Variable References in eDSL

### ISSUE THREAD

**Issue by goetzrrGit** [NASA-AMMOS/aerie#1247]
Carter from Clipper gave a presentation about the need for a `ReferenceArgument` for there SSF creation downstream. The SeqJSON `SymbolArgument` and `VariableDeclaration` aren’t going to work for them. I believe this is going to be a problem for multiple missions at JPL

**Comment by dandelany** [comment]
@goetzrrGit presented a proposal for these changes today (12/7) to SeqGen folks & got good feedback - more investigation & work needed.

**Comment by goetzrrGit** [comment]
[Aerie-Refrence-Variable.pptx](https://github.com/NASA-AMMOS/aerie/files/13967368/Aerie-Refrence-Variable.pptx)
