### ISSUE TITLE
Database unresponsive if many users create branches of the same plan at the same time

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#1252]
### Checked for duplicates

No - I haven't checked

### Is this a regression?

No - This is a new bug

### Version

2.1.0

### Describe the bug

In a multi-user test we were able to get the database to stop responding by having many people (~8) create branches of the same plan at the same time. The plan we used was from Clipper Thread Test 6 - a six week plan with about 200 activities. The system eventually recovered, but there was at least 5 min during which Aerie was completely unresponsive.

We attempted this twice with everyone creating branches from the same parent, and the system became unresponsive both times. We also tried with people branching from different plans, and did not reproduce the issue (branches were created quickly and successfully).

It is likely that this issue is what occurred during TT-6: https://github.com/NASA-AMMOS/aerie/issues/1044

### Reproduction

Have a bunch of people create branches at the same time. The size and complexity of the plan is probably important. Contact me for the plan that we used.

### System Info

```shell
Chrome
```

### Severity

Critical

**Comment by dandelany** [comment]
Thanks for the report @parkerabercrombie - we'll prioritize this issue. Sending to @Mythicaeda to work on re-testing & investigation.
