### ISSUE TITLE
Template build.gradle file for constraints/goals users

### ISSUE THREAD

**Issue by JoelCourtney** [NASA-AMMOS/aerie#1298]
Make a build.gradle file to provide to users for managing a gradle project of constraints/goals/conditions. Needs to provide easy-to-use tasks for building individual jars for each goal/constraint/etc. Look into using source sets to make this easier.

**Comment by skovati** [comment]
Created an example project in `procedural/examples/foo-procedures` that has a `build.gradle` file that automatically builds one jar per scheduling procedure / constraint

**Comment by skovati** [comment]
See https://github.com/NASA-AMMOS/aerie/issues/1453 for further work on integrating this into a starter repo
