### ISSUE TITLE
Make Aerie-Dev Send a Notification if DB Migrations Fail

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#1422]
Currently, if Aerie-Dev fails a DB migration, we don't know about it until someone happens to stumble across it. It should instead notify us that it failed so that we can investigate and fix these failures early.

This notification can be by email or a slackbot.

**Comment by skovati** [comment]
Created a slack bot, and updated the CD script to post status updates to `nasa-ammos-aerie-ops`. The bot will `@channel` with a warning if we ever fail DB migrations. No related PR for this issue, as the changes are internal to our dev deployment.
