### ISSUE TITLE
Sequence Expansion with Channel and Parameter Dictionaries

### ISSUE THREAD

**Issue by goetzrrGit** [NASA-AMMOS/aerie#1439]
### Checked for duplicates

No - I haven't checked

### Alternatives considered

No - I haven't considered

### Describe the feature request

The new user editor uses Channel and Parameter dictionaries. We want to use this on the expansion side as well. 

- [ ] Convert expansion rules to using parcels 
- [ ] Convert expansion sets to using parcels 
- [ ] Support uploading the 3 types of dictionaries Command, Channel, Parameters
- [ ] Typecheck against Channel and Parameter dictionary types
- [ ] Support command expansion and sequence generation with the Channel and Parameter Dictionary. 
- [ ] Update e2e test to support parcels

**Comment by dandelany** [comment]
Merged & done.
