### ISSUE TITLE
Enable a scheduling goal/procedure to appear in a specification multiple times

### ISSUE THREAD

**Issue by mattdailis** [NASA-AMMOS/aerie#1449]
_Originally posted by @mattdailis in https://github.com/NASA-AMMOS/aerie/issues/1296#issuecomment-2116162986_

Splitting out the notion of goal invocations into a separate piece of work from #1296

Scheduling procedures can take parameters - this feature is included in procedural scheduling.

A logical extension of that idea is to allow the same procedure to be _invoked_ multiple times in a scheduling specification - after all, the same procedure provided with different arguments may have very different behavior.

One note that occurred to us: there may be reasonable use cases for including the same scheduling goal or procedure in a scheduling specification multiple times, even without parameters, or even if the parameters are the same for both invocations. This is because the order of scheduling goals is significant - it may well be that there is a mutual dependency between some goals.

**Comment by dandelany** [comment]
Done in procedural scheduling branch
