### ISSUE TITLE
Aerie AMPCS parsing fails on empty and self-closing tags

### ISSUE THREAD

**Issue by cartermak** [NASA-AMMOS/aerie#1466]
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

No - This is a new bug

### Version

2.11.0

### Describe the bug

When uploading a command dictionary with empty or self-closing XML tags, I get an error from (I think) the sequencing server that looks to be coming from the AMPCS dictionary parsing module. 

### Reproduction

Upload an XML dictionary with empty or self-closing XML tags (e.g., `<description></description>` or `<description/>`). Aerie will fail to parse the dictionary. Stack trace from error response included below.

### Logs

```shell
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Module.parse (file:///app/node_modules/@nasa-jpl/aerie-ampcs/dist/index.js:315:62)
    at file:///app/build/app.js:110:38
    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:101:15)
    at next (/app/node_modules/router/lib/route.js:142:13)
    at Route.dispatch (/app/node_modules/router/lib/route.js:107:3)
    at handle (/app/node_modules/router/index.js:421:11)
    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:101:15)
    at /app/node_modules/router/index.js:288:22
    at processParams (/app/node_modules/router/index.js:568:12)
    at next (/app/node_modules/router/index.js:282:5)
```

### System Info

```shell
Local or AWS Aerie deployment; Firefox on MacOS.
```

### Severity

Moderate

**Comment by dandelany** [comment]
Thanks @cartermak - I have a [PR with a fix](https://github.com/NASA-AMMOS/aerie-ampcs/pull/9) for this in the underlying aerie-ampcs repository, will update again once it's reviewed and released.

**Comment by dandelany** [comment]
Remaining to do before this is fully fixed:
- [x] Review & merge [`aerie-ampcs` PR](https://github.com/NASA-AMMOS/aerie-ampcs/pull/9)
- [x] Update `aerie-ampcs` package version (1.0.6)
- [x] Create new NPM auth token and update AMPCS repo to use it
- [x] Publish new package version to NPM registry
- [x] Publish tagged release on aerie-ampcs repo
- [ ] Update to v1.0.6 in Aerie package.json, PR, and cherry-pick to 2.11.1 branch
