### ISSUE TITLE
Scheduler warnings on timing precision

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#458]
The scheduler generates many warnings of the form:

```
aerie_scheduler | [scheduler-agent] WARN gov.nasa.jpl.aerie.scheduler.constraints.activities.ActivityCreationTemplate - 
Root-finding is likely to fail as activity has an uncontrollable duration and the timing precision is 0. 
Setting it for you at 1s. 
Next time, use withTimingPrecision() when building the template.
```

But there is no way to specify a timing precision within the scheduling goal DSL, neither on the `CoexistenceGoal` itself nor on the `ActivityTemplate` as indicated.

Here is an example goal that causes the problem:

```ts
export default (): Goal => {
  return Goal.CoexistenceGoal({
    forEach: Real.Resource(Resources['/geometry/altitude_jupiter_km']).lessThan(165000),
    activityTemplate: ActivityTemplates.BGSet({
      primaryBody: 'PLUS_Y_NADIR_DECK',
      primaryTarget: 'PLANET',
      primarySpeedOfLightCorrection: 'NEGATIVE',
      secondaryBody: 'PLUS_X_ARRAY_AXIS',
      secondaryTarget: 'APPROACH_UNIQUE_X',
      secondarySpeedOfLightCorrection: 'ZERO',
    }),
    startsAt: TimingConstraint.singleton(WindowProperty.START),
  });
};
```

Internal ticket: https://jira.jpl.nasa.gov/browse/AERIEQS-341

**Comment by adrienmaillard** [comment]
Context: this precision parameter is used for determining the termination condition in the search when placing activities with uncontrollable durations. When the end time of the activity falls into [target-precision, target+precision], we stop the search.

Timing precision could be set by the user either in goals or in scheduler part of the mission model. I think we need both.
