### ISSUE TITLE
Add content-relevant page titles

### ISSUE THREAD

**Issue by JoelCourtney** [NASA-AMMOS/aerie#473]
It would be helpful if the page title included things like the plan name in the timeline view, the constraint/goal name in the constraints and scheduling editors, and the parent and child branch names in merge review, instead of just "Aerie" for all pages.

**Comment by camargo** [comment]
So we actually already have a UI ticket for this one: https://github.com/NASA-AMMOS/aerie-ui/issues/236
Closing. Added a link to this ticket from the UI one for reference.

**Comment by JoelCourtney** [comment]
Oh cool. BTW github has keywords for duplicates:

**Comment by JoelCourtney** [comment]
Duplicate of https://github.com/NASA-AMMOS/aerie-ui/issues/236
