### ISSUE TITLE
Create getSequenceSeqJsons action to generate seqJsons in bulk

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#489]
Currently the [getSequenceSeqJson action](https://github.com/NASA-AMMOS/aerie/blob/develop/deployment/hasura/metadata/actions.yaml#L42) ([endpoint in sequencing server](https://github.com/NASA-AMMOS/aerie/blob/develop/sequencing-server/src/app.ts#L542)) takes only a single `seqId` and returns a single `seqJson`. Our users currently call this API in a loop and automate the generation of `seqJson` for many sequences (currently 50-100 per plan). We need a bulk version of this API that allows for passing a list of `seqIds` to return a list of generated `seqJsons`.

For API consistency we should also do this for the [getUserSequenceSeqJson action](https://github.com/NASA-AMMOS/aerie/blob/develop/deployment/hasura/metadata/actions.yaml#L46).

**Comment by dyst5422** [comment]
If you'll let me, I'd love to tackle this tomorrow.

**Comment by camargo** [comment]
@dyst5422 That would be amazing. Let me know if you need push access to the repo - I think you should have it but I may need to add you to a new external collaborator team.

**Comment by dyst5422** [comment]
Are we confining this to a single simulation dataset/ command dictionary?

For example, we currently have
```gql
type Query {
  getSequenceSeqJson(
    seqId: String!
    simulationDatasetId: Int!
  ): GetSeqJsonResponse!
}
```
Do we want
```gql
type Query {
  getSequenceSeqJson(
    seqIds: [String!]!
    simulationDatasetId: Int!
  ): GetSeqJsonResponse!
}
```
or
```gql
input GetSequenceSeqJsonsInput {
  seqId: String!
  simulationDatasetId: Int!
}

type Query {
  getSequenceSeqJsons(
    inputs: [GetSequenceSeqJsonsInput!]!
  ): [GetSeqJsonResponse!]!
}
```

the first confining the scope to a single simulation dataset, while the second allows for operating on multiple simulation datasets.

I'm inclined to say that the true use-case here is for doing these in bulk for a single plan (or against a single command dictionary), so the former is a more direct solution to that. If you think there is a use-case for the latter (or even that we might want the flexibility of that latter) we can do that.

Implementation-wise, doing the former has greater opportunity for optimization.

**Comment by dyst5422** [comment]
Another couple clarifications:

Naming-wise, I think it might be good to put "bulk" somewhere in the action for clarity.

Do we want to move toward deprecating the singular actions in favor of the bulk by adding the @deprecated() graphql directive? (reduce long term maintenance burden by removing the singular ones)

**Comment by camargo** [comment]
> Are we confining this to a single simulation dataset / command dictionary?   

I actually like the latter just because it is a little more general for bulk querying. That said the former is the true use-case we are seeing right now so I'm good if we move forward with that. Especially if we can optimize it more. For the latter can it be similarly optimized if we collect all the same `simulationDatasetIds` in the list so we don't query the simulation multiple times? What makes the former more optimizable than the latter?

> Naming-wise, I think it might be good to put "bulk" somewhere in the action for clarity.

Agree

> Do we want to move toward deprecating the singular actions in favor of the bulk by adding the @deprecated()

Yes that sounds great

**Comment by dyst5422** [comment]
> What makes the former more optimizable than the latter?
Was thinking of the SQL we use to bulk grab data for the operation, but I found that we already do the necessary joins and can just pull the extra fields in order to do the appropriate bucketing on the server.

I'm ~70% done with this (delayed by the holidays) but hoping to get a PR out this week

**Comment by dyst5422** [comment]
Got this done - save for docs.

@camargo I do indeed need some permissions to push.

I appear to be a member to the org on GitHub still, so not sure what changed.

**Comment by camargo** [comment]
@dyst5422 Try now. I added you to the external team.
