### ISSUE TITLE
Expanded seqJSON should include metadata to trace back to source activity

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#504]
- Add metadata fields to seqJSON header to indicate planID, simulation data set ID
- Add metadata per command to indicate simulated activity instance ID

**Comment by dyst5422** [comment]
~~Fairly certain bullet point 2 is complete already https://github.com/NASA-AMMOS/aerie/blob/develop/sequencing-server/src/defaultSeqBuilder.ts#L17~~

Nope, that only does so for errors.

[This](https://github.com/NASA-AMMOS/aerie/blob/develop/sequencing-server/src/worker.ts#L109) however does seem to indicate that we're adding the metadata to the commands for simulated activity instance id

[Tests](https://github.com/NASA-AMMOS/aerie/blob/develop/sequencing-server/test/sequence-generation.spec.ts#L174-L301) confirm that is occurring as well

**Comment by dyst5422** [comment]
Happy to take this one. Should be a quick change.
