### ISSUE TITLE
An activity directive's type shouldn't be mutable once added to the plan

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#522]
Currently updating an activity directive via the API allows one to mutate the directive's start time, parameters, and activity type. The activity type shouldn't be mutable. Changing the type amounts to creating a new directive of a different activity type within the plan. How do we enforce this at the database level?

Migrated from [this internal ticket](https://jira.jpl.nasa.gov/browse/AERIE-1762).

**Comment by Twisol** [comment]
I think Hasura permissions allow you to prevent some columns from being set -- can we solve this from Hasura or do we really need to protect that column from even internal access?

**Comment by Mythicaeda** [comment]
With User Roles and Permissions, this has been resolved such that only the Hasura admin or `aerie-admin` role are able to change an activity's type, although technically a deployment can make a new role that makes the column mutable. Does this need to be blocked at the Postgres level or is this sufficient?

**Comment by camargo** [comment]
I think handling this at the Hasura permission level is sufficient because it's the user-facing API. We currently don't support users altering the DB tables directly through Postgres (and if they do it's up to them to keep things in sync).

**Comment by camargo** [comment]
Resolved via https://github.com/NASA-AMMOS/aerie/pull/940
