### ISSUE TITLE
Negative delay moves simulation time backward

### ISSUE THREAD

**Issue by mattdailis** [NASA-AMMOS/aerie#526]
Labeling this as a bug - but maybe it's a feature...? 😅

## Description
Type-wise, everything is fine - delay is defined to work on Duration, and that includes negative durations. However, I think this violates other invariants of the system - such as the invariant that the start offsets of resource profile segments are monotonically increasing.

`TaskStatus.Delayed` is perfectly happy to accept a negative duration:
https://github.com/NASA-AMMOS/aerie/blob/ad2e9c4130a09afea401daf15b3d0dbf7ccd801b/merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/types/TaskStatus.java#L10

The SimulationEngine is perfectly happy to schedule that task to be resumed in the past:
https://github.com/NASA-AMMOS/aerie/blob/ad2e9c4130a09afea401daf15b3d0dbf7ccd801b/merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/engine/SimulationEngine.java#L236-L238

This of course puts that task at the front of the job queue, so the next call to `extractNextJobs` contains this task, as well as the time (in the past) at which this task is scheduled.

The "delta" computation in the simulation driver will compute a negative delta and add it to the timeline: https://github.com/NASA-AMMOS/aerie/blob/ad2e9c4130a09afea401daf15b3d0dbf7ccd801b/merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationDriver.java#L73-L75

Interestingly - the timeline keeps a perfect record of all this - if time travel were somehow semantically acceptable, the timeline would capture it faithfully (particularly - it faithfully captures the direction of causality even when time steps backwards).

## Possible solutions
1. We can throw an error and tank simulation as soon as a negative delay is requested
2. We can clamp negative durations to ZERO - and perhaps issue a warning to alert the client that we've done this
3. (Far-fetched) We can try to give a reasonable semantics to time travel

**Comment by Twisol** [comment]
Oh, that's weird! Historically the behavior was 1, and I would argue for 1 even now, as negative delays are in my experience much more likely to be the result of a bug in the model than an actual desire to go backward in time. (A long while ago, the crash-on-negative-delay behavior did, in fact, help catch such bugs.)

**Comment by Twisol** [comment]
I wonder when the behavior changed?

**Comment by mattdailis** [comment]
Seems like it might have been this commit:

7526bb8992d7c4fa04a085f6a74187801d85fe80

**Comment by Twisol** [comment]
That commit only seems to speak to `defer`, which is a spawn-child-with-delay. I don't think that would influence a `delay` of the current task.

**Comment by mattdailis** [comment]
You're right - that commit simply deleted the exception, but by that time that method was no longer being called for `delay`.

This is the commit where `deferTo` ceased to be used for `delay`:
750cf7ba3109f80a57125d5e19cdbaa9a64e18c1

**Comment by Twisol** [comment]
I *did* expect it to be my fault, but of course it happened during the huge simulation engine reimplementation...

It looks like the refactor happened over that commit and the one before. The linked commit is the one where the old driver was switched over to use the new `SimulationEngine`, so that's where the check originally was and disappeared from -- and you can see in [this commit](https://github.com/NASA-AMMOS/aerie/commit/27e16841e6a300529d4f8d63c77061cb0bf23bac#diff-138e4b3239cc51dcc5033495a0a7188cc3a8b1bee83b07ef1fcf0d49862a00caR227-R229) that the check did not reappear in the analogous location in the new engine. (GitHub collapses the relevant file by default, apparently, so look at SimulationEngine.java lines 227-229.)

**Comment by Twisol** [comment]
I think all we need to do to fix this issue now is add the following line to the branch handling `Delayed` statuses.

```
if (s.delay().isNegative()) throw new IllegalArgumentException("Cannot schedule a task in the past");
```

**Comment by Twisol** [comment]
> You're right - that commit simply deleted the exception, but by that time that method was no longer being called for `delay`.
> 
> This is the commit where `deferTo` ceased to be used for `delay`: [750cf7b](https://github.com/NASA-AMMOS/aerie/commit/750cf7ba3109f80a57125d5e19cdbaa9a64e18c1)

Actually, it looks like the old `SimulationDriver` didn't even handle `TaskStatus.Delayed` properly, so the true source of this bug is even earlier.

```
        } else if (status instanceof TaskStatus.Delayed<?> s) {
          queue.deferTo(queue.getElapsedTime().plus(s.delay()), info.id);
```

**Comment by mattdailis** [comment]
> Actually, it looks like the old `SimulationDriver` didn't even handle `TaskStatus.Delayed` properly, so the true source of this bug is even earlier.
> 
> ```
>         } else if (status instanceof TaskStatus.Delayed<?> s) {
>           queue.deferTo(queue.getElapsedTime().plus(s.delay()), info.id);
> ```

`queue.deferTo` included a non-negative check - so on that previous commit I believe I did get an exception in my manual git bisect experiment

**Comment by Twisol** [comment]
> `queue.deferTo` included a non-negative check - so on that previous commit I believe I did get an exception in my manual git bisect experiment

Ah, okay! Then it's definitively my fault :)
