### ISSUE TITLE
Record simulated activity ID per expanded command

### ISSUE THREAD

**Issue by mattdailis** [NASA-AMMOS/aerie#529]
Goal is to include simulated activity ID associated with each expanded command in the seq JSON

**Comment by camargo** [comment]
@mattdailis Should we use the `metadata` field in the command step seq JSON for this?

**Comment by camargo** [comment]
@dyst5422 We are having some trouble tracing through the code to make this change. Any tips on where to start?

**Comment by dyst5422** [comment]
The simulated activity id should already be included in the command metadata based on the code [here](https://github.com/NASA-AMMOS/aerie/blob/develop/sequencing-server/src/worker.ts#L109).

And we have a test to validate that [here](https://github.com/NASA-AMMOS/aerie/blob/develop/sequencing-server/test/sequence-generation.spec.ts#L190) where we check that a query of `getSequenceSeqJson` returns that information (see the specifics of the test query [here](https://github.com/NASA-AMMOS/aerie/blob/c8b73f4a9a43772932275667a2be673e5f6310da/sequencing-server/test/testUtils/Sequence.ts#L35)).

So where are we missing this behavior?

**Comment by dyst5422** [comment]
Also, this might duplicate part of #504

**Comment by cohansen** [comment]
Confirmed that `simulatedActivityId` is already there, thanks @dyst5422 !
