### ISSUE TITLE
Update all dependencies for the sequencing-server

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#536]
There is a [security alert](https://github.com/NASA-AMMOS/aerie/security/dependabot/4) for the [sequencing-server](https://github.com/NASA-AMMOS/aerie/tree/develop/sequencing-server). We should just do a pass over [all the dependencies](https://github.com/NASA-AMMOS/aerie/blob/develop/sequencing-server/package.json) and update them to the latest versions.

**Comment by cohansen** [comment]
It looks like we're using `express@^5.0.0-beta.1` which requires `qs@6.9.6` and the fixed version is `6.9.7`. There isn't a newer beta release but I can keep my eye out for a release that fixes this.

I'll still update the other dependencies though!

**Comment by dyst5422** [comment]
As a reference, [this async error handling behavior](https://expressjs.com/en/guide/migrating-5.html#rejected-promises) is why we decided to push to express 5 while it's still in beta.
