### ISSUE TITLE
Support entire seq JSON spec in the sequence eDSL

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#550]
Currently only a subset of the seq JSON spec is supported in the sequence eDSL. This task is to support the entire spec. Can some of the TypeScript be generated from the seq JSON schema so we don't have to continue to keep them in sync?
This should include supporting the latest seq JSON spec.

**Comment by goetzrrGit** [comment]
example of what is possible:

```
export default () =>
  Sequence.new({
    seqId: '',
    metadata: {},
    A`2020-20-19939`.ground(args:{})
    A`2020-20-19939`.BAKE_BREAD()
    steps: [ commands, ground, loads, activates, etc. ],
    request: [ steps: [commands, ground, etc.] , steps : [etc.] ],
  });

```

**Comment by goetzrrGit** [comment]
I proposed breaking up this into sections so it is more manageable. 

- Incorporate the JSON spec into the Aerie Repo and give EDSL access to the full JSON Spec
- Make Sequence EDSL API use this new SPEC and possibly try to preserve backward compatibility for now. 

ex.
 ```
Sequence.new({
    seqId: '',
    metadata: {},
    steps: [ commands, ground, loads, activates, etc. ],
    request: [],
    
    commands : [] <--- preserve backward compatibility for now
  });

```


- Wrap the current EDSL into the 4 command types (Activate | Command | GroundBlock | GroundEvent | Load) and make the eDSL expand the `step` array

ex.
 ```
Sequence.new({
    seqId: '',
    metadata: {},
    steps: [ Ground.new(A``2020-060T03:45:19`.BakeBread, { name : "GroundBlock1" }) , etc.],
    request: [],
    
    commands : [] <--- Remove
  });
```


- EDSL Cleanup - Try to clean up the code a little and merge more of the spec and EDSL API together to create a tighter coupling. 
- Look at how we can write more custom eDSL to help to make this easier to write. For example `request` is a more complicated structure than `steps`

**Comment by camargo** [comment]
This issue has been decomposed into the following issues:

1. https://github.com/NASA-AMMOS/aerie/issues/609
2. https://github.com/NASA-AMMOS/aerie/issues/610
3. https://github.com/NASA-AMMOS/aerie/issues/611
4. https://github.com/NASA-AMMOS/aerie/issues/612
