### ISSUE TITLE
Long delay before UI acknowledges simulation request status

### ISSUE THREAD

**Issue by mattdailis** [NASA-AMMOS/aerie#595]
This ticket to be filled out with more information as it becomes known.

AERIEQS ticket: [AERIEQS-427](https://jira.jpl.nasa.gov/browse/AERIEQS-427)

Sometimes, when clicking the simulate button, the UI does not display any simulation status for a very long time.

I've observed this a couple times locally - unfortunately I don't have screenshots or data at the moment - I will supply them if I see it again.

What I did observe was what appeared to be a deadlock. I ran the query below and saw that some queries (subscriptions from the UI, I think?) were both blocking and blocked by a `create partition` query. I interpret this to mean that the UI subscription to the simulation results is preventing the simulation from starting - and somehow neither query is able to go through. (For a deadlock to happen, there need to be at least two locks involved - so I'm a little unsure what the salient locks are here).

<details>
<summary>
SQL to see what queries are blocked by what other queries
</summary>

```sql
SELECT blocked_locks.pid     AS blocked_pid,
       blocked_activity.usename  AS blocked_user,
       blocking_locks.pid     AS blocking_pid,
       blocking_activity.usename AS blocking_user,
       blocked_activity.query    AS blocked_statement,
       blocking_activity.query   AS current_statement_in_blocking_process
FROM  pg_catalog.pg_locks         blocked_locks
          JOIN pg_catalog.pg_stat_activity blocked_activity  ON blocked_activity.pid = blocked_locks.pid
          JOIN pg_catalog.pg_locks         blocking_locks
               ON blocking_locks.locktype = blocked_locks.locktype
                   AND blocking_locks.database IS NOT DISTINCT FROM blocked_locks.database
                   AND blocking_locks.relation IS NOT DISTINCT FROM blocked_locks.relation
                   AND blocking_locks.page IS NOT DISTINCT FROM blocked_locks.page
                   AND blocking_locks.tuple IS NOT DISTINCT FROM blocked_locks.tuple
                   AND blocking_locks.virtualxid IS NOT DISTINCT FROM blocked_locks.virtualxid
                   AND blocking_locks.transactionid IS NOT DISTINCT FROM blocked_locks.transactionid
                   AND blocking_locks.classid IS NOT DISTINCT FROM blocked_locks.classid
                   AND blocking_locks.objid IS NOT DISTINCT FROM blocked_locks.objid
                   AND blocking_locks.objsubid IS NOT DISTINCT FROM blocked_locks.objsubid
                   AND blocking_locks.pid != blocked_locks.pid

          JOIN pg_catalog.pg_stat_activity blocking_activity ON blocking_activity.pid = blocking_locks.pid
WHERE NOT blocked_locks.granted;
```

</details>

Without truly understanding the root cause - I've played around with an option that creates partitions without requiring the `ACCESS EXCLUSIVE` lock, based on [this](https://stackoverflow.com/a/67016755) StackOverflow answer.

Here is the branch with my experimentation: https://github.com/NASA-AMMOS/aerie/compare/develop...prototype/avoid-deadlock-partition-creation

EDIT: Now, it is possible that this is not a deadlock, but merely a lock waiting for a long query - possibly the long query from #574 is blocking the next simulation from starting.

**Comment by parkerabercrombie** [comment]
I don't know if it's related, but I'm seeing these errors in the log around the time the simulation UI becomes unresponsive:
```
hasura              | {"detail":{"http_info":{"content_encoding":null,"http_version":"HTTP/1.1","ip":"172.27.0.1","method":"GET","status":404,"url":"/rstatic/dist/2.js"},"operation":{"error":{"code":"not-found","error":"resource does not exist","path":"$"},"raw_query":"","request_id":"6b819585-fef9-4cd8-8699-0331954cbb76","request_mode":"error","response_size":65},"request_id":"6b819585-fef9-4cd8-8699-0331954cbb76"},"level":"error","timestamp":"2023-01-19T21:35:01.995+0000","type":"http-log"}
hasura              | {"detail":{"http_info":{"content_encoding":null,"http_version":"HTTP/1.1","ip":"172.27.0.1","method":"GET","status":404,"url":"/rstatic/dist/2.js"},"operation":{"error":{"code":"not-found","error":"resource does not exist","path":"$"},"raw_query":"","request_id":"cc616eec-a0f0-43b3-a665-9f84ffa47b72","request_mode":"error","response_size":65},"request_id":"cc616eec-a0f0-43b3-a665-9f84ffa47b72"},"level":"error","timestamp":"2023-01-19T21:36:59.089+0000","type":"http-log"}
```

**Comment by parkerabercrombie** [comment]
And shortly after the above hasura error this showed up in the log:
```
aerie_merlin_worker_2 exited with code 137
postgres            | 2023-01-19 21:37:33.656 UTC [154] ERROR:  deadlock detected
postgres            | 2023-01-19 21:37:33.656 UTC [154] DETAIL:  Process 154 waits for ShareRowExclusiveLock on relation 16597 of database 16386; blocked by process 90.
postgres            | 	Process 90 waits for RowExclusiveLock on relation 16611 of database 16386; blocked by process 154.
postgres            | 	Process 154: create table profile_segment_72 partition of profile_segment for values in (72)
postgres            | 	Process 90: insert into profile_segment (dataset_id, profile_id, start_offset, dynamics, is_gap)
postgres            | 	  values ($1, $2, $3::interval, $4::json, $5)
postgres            | 2023-01-19 21:37:33.656 UTC [154] HINT:  See server log for query details.
postgres            | 2023-01-19 21:37:33.656 UTC [154] STATEMENT:  create table profile_segment_72 partition of profile_segment for values in (72)
postgres            | 2023-01-19 21:37:33.666 UTC [90] LOG:  unexpected EOF on client connection with an open transaction
merlin_worker_1     | Exception in thread "main" java.lang.Error: Failed to create partitions for simulation dataset id 72
merlin_worker_1     | 	at gov.nasa.jpl.aerie.merlin.server.remotes.postgres.PostgresResultsCellRepository.claim(PostgresResultsCellRepository.java:114)
merlin_worker_1     | 	at gov.nasa.jpl.aerie.merlin.worker.MerlinWorkerAppDriver.main(MerlinWorkerAppDriver.java:71)
```

**Comment by mattdailis** [comment]
@parkerabercrombie if you still have this database running, could you look up the relation ids mentioned in the log you posted above?

You can do this by opening hasura to `http://localhost:8080/console/data/sql` (or wherever you have hasura deployed), selecting `AerieMerlin` from the "Database" dropdown. Paste the following sql code into the text box and click "Run!":

```sql
select 16597::regclass as relation_16597, 16611::regclass as relation_16611;
```

If that's not possible, that's okay, I can take my best guess at which tables those refer to

**Comment by mattdailis** [comment]
I've managed to reproduce the deadlock in a manual psql session. I did the following:

1. Disable the workers, so they don't pick up a new simulation run
2. Request a new simulation using the UI. Note the dataset_id. (In my case it was `7`)
3. Start two `psql` sessions in two terminals.
4. In Session 1, run `insert into profile (dataset_id, name, type, duration) values (7, 'fred', '{}', '1 second');`
5. In Session 2, run `create table profile_segment_7 partition of profile_segment for values in (7);`
6. In Session 1, run `insert into profile_segment (dataset_id, profile_id, start_offset, dynamics, is_gap) values (7, 10147, '0 seconds', '{}', false);` (this id should match the id assigned to the profile in step 4, you'll need to query for it)

Observe a deadlock error:
```
ERROR:  deadlock detected
LINE 1: insert into profile_segment (dataset_id, profile_id, start_o...
                    ^
DETAIL:  Process 2110 waits for RowExclusiveLock on relation 16621 of database 16386; blocked by process 2111.
Process 2111 waits for ShareRowExclusiveLock on relation 16607 of database 16386; blocked by process 2110.
```

In step 4, Session 1 locked `profile` with a `RowExclusiveLock`.

In step 5, Session 2 locked `profile_segment` with an `AccessExclusiveLock`, and blocked while trying to acquire a `ShareRowExclusiveLock` on `profile`.

In step 6, Session 1 attempts to acquire a `RowExclusiveLock` on `profile_segment`, and creates a deadlock - since that lock conflicts with a lock held by Session 2.

EDIT: I realized just now that I should have had the two sessions reference two different datasets - I'll try that now, but I think this behavior is independent of the specific dataset_id.

**Comment by parkerabercrombie** [comment]
> if you still have this database running, could you look up the relation ids mentioned in the log you posted above?

Unfortunately I dropped that database. Sorry!

**Comment by mattdailis** [comment]
> Here is the branch with my experimentation: https://github.com/NASA-AMMOS/aerie/compare/develop...prototype/avoid-deadlock-partition-creation

What I've been able to establish is that the changes in the above branch will help avoid deadlock - but that doesn't necessarily solve the problem.

Commands that alter a table (including adding a partition) conflict with commands that add data to the table (i.e. insert statements).

As it stands, a simulation worker creates partitions for its results just after claiming a simulation request, but just before starting a simulation. If, at that moment, another simulation worker is in the middle of writing results to the database - the two simulation workers' desires conflict. The second simulation worker claims locks on any tables that the first simulation worker hasn't gotten to - resulting in a deadlock.

It may take some time for postgres to notice the deadlock - when it does, it kills one of the transactions.

The branch mentioned above avoids the deadlock by preventing the second simulation worker from blocking the first one. While this does make sure that the second simulation request is eventually able to succeed - it means that the next simulation can't start until the previous one has finished writing - which is undesirable.

**Comment by mattdailis** [comment]
The vulnerability to deadlock was introduced by #411, which sped up the time to write simulation results, at the expense of interfering with other workers' ability to start simulations. Prior to that change, every insert statement was immediately committed, releasing its locks.

So - we could move back towards writing simulation results in multiple transactions - perhaps not a transaction per statement, but some kind of batching.

Orthogonally to that, we can let the simulation get underway before the partition is created - leaving a separate thread to block until it can make the partition. We'd need to make sure that the partition was indeed created before attempting to write any data.

Further brainstorming - we can create the new tables, and write data to them, and attach them to the dataset later. This could offer the best parallelism as far as writing the data - but queries from the API would need to wait until the new tables are attached.

**Comment by Twisol** [comment]
Looking back at your repro:

> * In Session 1, run `insert into profile (dataset_id, name, type, duration) values (7, 'fred', '{}', '1 second');`
> 
> * In Session 2, run `create table profile_segment_7 partition of profile_segment for values in (7);`
> 
> * In Session 1, run `insert into profile_segment (dataset_id, profile_id, start_offset, dynamics, is_gap) values (7, 10147, '0 seconds', '{}', false);` (this id should match the id assigned to the profile in step 4, you'll need to query for it)

I notice that we create `profile_segment_#`, but write to `profile_segment`. Is it possible to write to `profile_segment_#` directly, rather than routing it through the partitioning? Would this avoid the contention outright?

The [postgres docs](https://www.postgresql.org/docs/current/ddl-partitioning.html) say this, from which I infer that writing directly to a partition is okay:

> After creating partitions of `measurement_y2006m02`, any data inserted into `measurement` that is mapped to `measurement_y2006m02` (or data that is directly inserted into `measurement_y2006m02`, which is allowed provided its partition constraint is satisfied) will be further redirected to one of its partitions based on the `peaktemp` column.

**Comment by Twisol** [comment]
(There's even a chance that writing to the partition directly will give better performance, since Postgres wouldn't need to figure out which partition it needs to write each row to -- just check that each row obeys the partition constraint.)

**Comment by mattdailis** [comment]
> Is it possible to write to profile_segment_# directly, rather than routing it through the partitioning?

That's certainly worth a try! Part of the issue is contention on the `profile` table (since profile_segment refers to it by foreign key), but I can't claim to totally grok the subtleties here.

**Comment by mattdailis** [comment]
Here's my attempt at a sequence diagram for network messages related to simulation, to hopefully help with building a shared mental model. `par` means "in parallel" - so the UI subscription is happening in parallel with the Worker's work.

The discussion above is about what happens when two workers reach the right side of this diagram concurrently - so one is in the middle of writing simulation results, while the other is trying to "create partitions".

```mermaid
sequenceDiagram
  autonumber
  participant ui as UI
  participant hs as Hasura
  participant ms as Merlin Server
  participant db as Postgres
  participant w as Worker

  ui->>hs:simulate request
  hs->>ms:simulate request
  ms->>db:insert into simulation_dataset
  par Worker running simulation
  db--)w:notify
  w->>db:attempt to claim simulation
  db->>w:claim acknowledgement
  w->>db:create partitions
  db->>w:sim config, plan details
  activate w
  w-->w: Run simulation to completion, in memory
  w->>db:simulation results
  w->>db:mark simulation complete
  deactivate w
  and UI awaiting sim completion
  db->>ms:simulation dataset id
  ms->>hs:simulation dataset id
  hs->>ui:simulation dataset id
  ui->>hs:subscribe to sim status
  loop every second
   hs->>db:poll for sim status
   db->>hs:simulation status
  end
  hs->>ui:simulation status (if changed)
  ui->>hs: query for sim results
  hs->>db: query for sim results
  db->>hs: sim results
  hs->>ui: sim results
  end
```

**Comment by Twisol** [comment]
It's awfully cool that you can describe sequence diagrams in GitHub-flavored Markdown -- unfortunately I'm not sure it's helping me understand the root cause of the deadlock.

In your repro, why is it essential that different `psql` sessions create the partition and insert into it? The INSERT should be causally ordered relative to the CREATE TABLE, so it isn't clear how that contributes to a deadlock.

**Comment by Twisol** [comment]
> I've managed to reproduce the deadlock in a manual psql session.

Are steps 4 and 6 in Session 1 in a transaction, or do they commit immediately? If we perform step 6, it seems like step 4 must already have completed -- so are we still holding the `RowExclusiveLock` from step 4?

**Comment by mattdailis** [comment]
> The INSERT should be causally ordered relative to the CREATE TABLE, so it isn't clear how that contributes to a deadlock.

Ah, I left out a crucial detail - each psql session starts a transaction. Here's the full manual "script" I followed - `1:` and `2:` denote psql sessions.

```
1: begin
1: create table profile_segment_8 partition of profile_segment for values in (8);
1: commit

1: begin
1: insert into profile (dataset_id, name, type, duration) values (8, 'fred', '{}', '1 second');

2: begin
2: create table profile_segment_9 partition of profile_segment for values in (9);
-- blocks due to lock conflict on `profile` table

1: insert into profile_segment (dataset_id, profile_id, start_offset, dynamics, is_gap) values (8, 10147, '0 seconds', '{}', false);
-- blocks due to lock conflict on `profile_segment` table, causing deadlock
```

**Comment by Twisol** [comment]
To summarize a Slack investigation between @mattdailis and myself, there appear to be *two* problems here:

* First, the partition creation requires an overly-strong lock. The [StackOverflow answer](https://stackoverflow.com/a/67016755) linked in the original PR provides a method to relax the strength of the lock sufficiently.
* Second, the partition creation somehow is blocked by pending inserts on `profiles`. If we move the initial creation of `profiles` rows into a separate transaction -- leaving the actual data load in the original transaction -- then there's no remaining contention between the inserts on one partition and the creation of another.

**Comment by mattdailis** [comment]
I've dug into the foreign key locking situation a bit. As far as I can tell, the reasoning is as follows:

When we run `alter table profile_segment attach partition profile_segment_#`, postgres needs to verify that all of the elements of `profile_segment_#` conform to the constraints defined on `profile_segment`. It doesn't know that `profile_segment_#` is, in fact, empty, and thus trivially satisfies any constraints.

So, postgres needs to check that the contents of `profile_segment_#` satisfy the foreign key constraint referencing the `profile` table. The situation postgres wants to avoid is one where, during the check, rows are deleted from `profile`, invalidating earlier parts of the check. (I suppose this is because "on delete cascade" triggers won't yet be enabled, until after the new partition is attached). To that end, postgres claims a lock on the `profile` table that conflicts with all concurrent modification (not only `delete`, but also `insert` and `update`).

In our case, this is a bit silly, because _we_ know that a) the new partition is empty and b) we aren't deleting from `profile` - we're inserting non-interfering profile definitions. However, postgres knows neither of those things. (Though, you would _think_ it could do something about (a)).

With the goal of not blocking new simulations from starting, this leaves us with a couple of options for how to proceed:
1. Remove the foreign key relationship from `profile_segment` to `profile`, and similarly from `event` to `topic`. This would allow partition creation to be completely independent from inserts
2. Guarantee that any transaction performing `insert`, `delete`, or `update` on `profile` or `topic` releases its locks in a timely fashion. Do partition creation concurrently with simulation to allow the simulation to proceed even though the locks are still held by the other transaction. Stream results into `profile_segment_#` directly before it is attached

I am attracted to the complete independence between simulation workers that option 1 promises. What do we stand to lose by removing these foreign keys? Would implementing these foreign keys "by hand" using triggers be a viable alternative?

What option 2 has going for it is that we already have plans to chunk up inserts. For long enough simulations, delay in lock acquisition would be masked behind the run time of the simulation itself. This does mean that all inserting workers will need to wait for these partition constraint conformance checks to complete - but those should hopefully be pretty quick, especially since the new partition already has the same constraints defined (courtesy of the "like" clause: `create table profile_segment_# (like profile_segment including constraints);`)

Open questions:
- Why do the one-command vs two-command options for creating partitions differ in the level of locks that they acquire?
- If/when we do bulk loading via `COPY FROM`, does that have different lock behavior from `INSERT`?

**Comment by Twisol** [comment]
To make sure I understand correctly --the ALTER TABLE-caused constraint check should be basically instant, because the partition being attached is empty; but because it takes a lock, it's forced to block and wait on any concurrent update to `profile`. Yes?

**Comment by mattdailis** [comment]
> To make sure I understand correctly --the ALTER TABLE-caused constraint check should be basically instant, because the partition being attached is empty; but because it takes a lock, it's forced to block and wait on any concurrent update to `profile`. Yes?

That is correct :+1: When I said `but those should hopefully be pretty quick`, I was thinking ahead to implications of Option 2, where we could have already streamed some results into the partition before we acquire the lock to attach it.

**Comment by Twisol** [comment]
Generally speaking, I'm more interested in option 2 (short transactions). Long-lived transactions are an antipattern for concurrency in general, so I'm hesitant to do anything biased in favor of long transactions. We should of course strive to avoid unnecessary concurrency hazards, like the too-strong lock with the one-clause form of partition attachment, but I don't think we should stake the consistency of our database in the process.

I'm nervous about relaxing the foreign key constraints, because while I have no doubt we could implement the system safely without them right now, I'm worried about the long-term maintenance implications. Constraints act as a global restriction; if you break them, you'll know. If we were to replace them with a local discipline on individual pieces of code that implicitly respect those constraints, we leave the door wide open to future code or changes not recognizing that constraint, and failing to respect it.

I'm not sure triggers will help much. They might count as a global restriction,  but I suspect they will end up taking the same locks the current foreign key constraint does -- though maybe not with the same timing.

One thing we might explore is partitioning `profile` itself. I'm not certain it will work, but if we're able to get the `profile_segments` partition to depend only on the analogous `profile` partition, maybe the locks will end up better scoped.

**Comment by Twisol** [comment]
I feel less and less confident in the "partition all the things" idea as I dwell on it, so maybe scrap that...

**Comment by Twisol** [comment]
Does the one-clause form of partition creation also incur the same lock on `profile`? If so, why? Postgres should know the table is empty, because it hasn't been constructed yet!

**Comment by mattdailis** [comment]
> Does the one-clause form of partition creation also incur the same lock on `profile`? Why? Postgres should know the table is empty, because it hasn't been constructed yet!

👆 👆 👆 

This question has sent me down quite the rabbit hole, and I haven't quite resurfaced 😅

**Comment by mattdailis** [comment]
> Why do the one-command vs two-command options for creating partitions differ in the level of locks that they acquire?

Sounds like the answer is "we weren't sure, so we erred on the safe side" rather than "this is the way it must be"

> I think that part of the reason that I did not research
that at the time is that the patch was incredibly complicated to get
working at all and I didn't want to take any risk of adding things to
it that might create more problems.
> ...
> I know that when I
developed the original patch, I thought about this case and decided my
brain was full. However, I do not recall whether I knew about any
specific problems that needed to be fixed, or just feared that there
might be some.

https://www.postgresql.org/message-id/CA%2BTgmoZxY_YpqCmNBYgQJTWLG4XF_0QjLwJ61W0_XK-_eig9vg%40mail.gmail.com

**Comment by Twisol** [comment]
That's... um.... comforting in a weird way.

**Comment by mattdailis** [comment]
This blog post from TimescaleDB gives a pretty good survey of this class of issue:

https://www.timescale.com/blog/how-timescaledb-solves-common-postgresql-problems-in-database-operations-with-data-retention-management/

> PostgreSQL has traditionally taken the view that concurrency is not extremely important for database operations while Data Definition Language (DDL) commands are run. Traditionally, this is true. Even today, DDL commands are usually run sufficiently infrequently that the database [can] take the performance hit of introducing DDL commands as synchronization points. 
>
> The emerging problems of heavy PostgreSQL users today are not usually performance problems but the fact that applications are often not written with an awareness of what these added synchronization points will mean. In my experience, these synchronization points themselves are a significant cause of database outages among large-scale PostgreSQL users.
>
> Timescale has been built to avoid the sort of locking problems that currently exist with PostgreSQL’s declarative partitioning simply because this is a common problem in time-series workloads.

**Comment by Twisol** [comment]
Interesting blog post! It's worth mentioning that we considered TimescaleDB to be a possible next evolutionary step in our use of Postgres when we first did a trade study among our database options. It's not clear to me that we need it for the issue under discussion, but it's a good tool to have at our disposal when we do.
