### ISSUE TITLE
Profile negation

### ISSUE THREAD

**Issue by JoelCourtney** [NASA-AMMOS/aerie#601]
We seem to be missing a key part of basic arithmetic in the profile department.

**Comment by dyst5422** [comment]
I know absolutely nothing about this, BUT I know that many implementations of subtraction are better modeled as addition of a negation as a way to reduce API surface area and limiting execution paths.

**Comment by JoelCourtney** [comment]
> many implementations of subtraction are better modeled as addition of a negation as a way to reduce API surface area and limiting execution paths

fair, I think I'm only going to implement `.negate`
