### ISSUE TITLE
Add resourceTypes table to database to make querying for them better

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#605]
The `resourceTypes` action can be slow. The Clipper `eurc` model for version `G23.0-RC1a` has `2180` profiles. It takes `~2646 ms` to query in Hasura, and the UI. We need a way to paginate the results. Add support for a cursor, filter, and search to the action to allow for clients to query for subsets of the `resourceTypes` (sort of like Hasura supports for regular database queries). 

We should add resource types to the database and obviate this action. Similar to what we do for activity types.

```gql
query GetResourceTypes($missionModelId: ID!) {
  resourceTypes(missionModelId: $missionModelId) {
    name
    schema
  }
}
```
```json
{
  "missionModelId": 1
}
```

**Comment by mattdailis** [comment]
For my own understanding, what does the UI use the resource types for?

**Comment by camargo** [comment]
Right now we use them to populate default UI view, and https://github.com/NASA-AMMOS/aerie-ui/pull/315 uses them to populate the dropdown of resources to select for which resources to plot.

**Comment by camargo** [comment]
Per @mattdailis https://jpl.slack.com/archives/CJ07FGRPH/p1677196008528159?thread_ts=1677195556.748839&cid=CJ07FGRPH
