### ISSUE TITLE
Constraints: avoid loading full simulation results into memory

### ISSUE THREAD

**Issue by mattdailis** [NASA-AMMOS/aerie#628]
Simulation results can get quite large - and it's quite likely that most resource profiles will not be referenced by any constraint.

The purpose of this ticket is to try to load the minimum amount required to check constraints.

The set of referenced resources if available here:
https://github.com/NASA-AMMOS/aerie/blob/35d274a6a5b95bba63c46a7f2e336c13545d354e/merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/GetSimulationResultsAction.java#L243-L245

This ticket would involve re-organizing the resource loading, so that it comes after goal parsing. Then, we can ask the parsed goals what resources they need, and load just those resources from the database.

**Comment by Twisol** [comment]
This could be a good driver for following up on the ideas @JoelCourtney and I discussed, around making constraint computation compute incrementally (feed in a new chunk of profile, output a new chunk of result) and without materializing all intermediate profiles.

**Comment by mattdailis** [comment]
> This could be a good driver for following up on the ideas @JoelCourtney and I discussed, around making constraint computation compute incrementally (feed in a new chunk of profile, output a new chunk of result) and without materializing all intermediate profiles.

Absolutely :+1: I suspect #488 may be related as well.

**Comment by Twisol** [comment]
Ah, yes, that'd be the one. (Sorry I never got around to that review...)

@JoelCourtney, I'm happy to pair sometime to try to work through the problems you encountered in the end.

**Comment by camargo** [comment]
https://github.com/NASA-AMMOS/aerie/pull/710
