### ISSUE TITLE
Expansion Set fails on Activity Type with same name as a command

### ISSUE THREAD

**Issue by cartermak** [NASA-AMMOS/aerie#635]
Aerie fails to create an expansion set which contains a rule for an activity type that has the same name as a command in the command dictionary (I hypothesize; that's the only logical link I've come up with). 

When creating the set, the API returns a TS2352 error (mildly redacted):

```
    Expansion set could not be type checked
    Caused by: [
        TypeError: TS2352 Conversion of type 'CommandStem<[{*command parameters*}], Record<string, any>>' to type '*activity type name*' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
        Type 'CommandStem<[{*command parameters*}], Record<string, any>>' is missing the following properties from type '*activity type name*': type, duration, startOffset, startTime, and 2 more.
    ]
```

**Comment by biqua** [comment]
This is a critical/blocking issue for Clipper command expansion. Could we get this bumped up in the minor fixes priority, and maybe get an estimate for when we could expect to see a fix? We need it by April (for TT-4) to avoid causing major issues.

Pinging @camargo for attention.

**Comment by camargo** [comment]
@biqua, @cohansen is going to take a look at this next sprint. Should be plenty of time to have a fix in before April.

**Comment by biqua** [comment]
Great, thank you! Let me or Carter know if there's anything you need from us.
