### ISSUE TITLE
Track constraint checking status in the database

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#637]
We need to reflect the status of constraint checking the database. This should be similar to how we store simulation and scheduling statuses.

**Comment by joswig** [comment]
We also need a design for persisting constraint check results. They currently aren't tracked and need to be re-run. If it makes sense we can split that into another issue

**Comment by cohansen** [comment]
I think we need to do both of these things at the same time, each `constraint_run` (or whatever this new table is called) record should contain the status of the result, and probably some other properties as well. I'll take a look at the db to see how scheduling and simulation handle this.
