### ISSUE TITLE
Uploading generated seqjson uses old list notation

### ISSUE THREAD

**Issue by cohansen** [NASA-AMMOS/aerie#668]
When uploading generated seqjson inside the Sequence Editor it generates the old list notation rather than the new object notation.

We may need to wait until we've updated to using the latest seqjson before addressing this ticket.

**Comment by camargo** [comment]
We need https://github.com/NASA-AMMOS/seq-json-schema/issues/6 first before we can fix. We decided to use the current-pass-by-name format with the updated Seq JSON spec (which will include the argument name).
