### ISSUE TITLE
Consistent templates for issue tickets and pull-requests

### ISSUE THREAD

**Issue by riverma** [NASA-AMMOS/aerie#673]
**Checked for duplicates**
 
 Yes - I've already checked
 
 **Alternatives considered**
 
 Yes - and alternatives don't suffice
 
 **Related problems**
 
 N/A
 
 **Describe the feature request**
 
 As part of the [NASA-AMMOS/slim project](https://nasa-ammos.github.io/slim/), we've been developing standardized issue templates and pull request templates to make it easier for projects to read and write tickets / pull-requests in a more consistent way.
 
 See our issue template examples for [bugs](https://github.com/nasa-ammos/slim/blob/main/documentation/starter-kits/ISSUE_TEMPLATES/github/bug_report.yml) and [new features](https://github.com/nasa-ammos/slim/blob/main/documentation/starter-kits/ISSUE_TEMPLATES/github/new_feature.yml) - pure Markdown versions also available. Please go [here](https://nasa-ammos.github.io/slim/documentation/starter-kits/#issue-templates) for further details.
 
 See an example of our pull request templates [here](https://github.com/nasa-ammos/slim/blob/main/documentation/starter-kits/ISSUE_TEMPLATES/github/PULL_REQUEST_TEMPLATE.md) and further described here. 
 
 If this is helpful, let me know. We can push out a pull-request with these templates for your repository. We can also work with you to customize this template if that's desired!
 
 Sample bug report:
 <img width='726' src='https://user-images.githubusercontent.com/3129134/218888638-7d076d2a-c8c4-4f07-8a4d-3cd4b327c60d.png'>
 
 Sample feature request:
 <img width='723' src='https://user-images.githubusercontent.com/3129134/218888642-8d26a440-1c51-46eb-9ff8-6b843fcb4b91.png'>
 
 Sample pull-request:
 <img width='653' src='https://user-images.githubusercontent.com/3129134/218887565-2e1a4f4e-7b87-436b-84a0-a082efb5c341.png'>

**Comment by camargo** [comment]
Hi @riverma thanks for the issue. We currently have an issue for this (https://github.com/NASA-AMMOS/aerie/issues/652) so I'm going to close.
