### ISSUE TITLE
Look into returning the last simulation results at the end of scheduling

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#676]
Currently we re-simulate at the end of scheduling. We should look into returning the last simulation the scheduler runs instead.

**Comment by Twisol** [comment]
This should be balanced carefully against any predicted capability for the scheduler to use different simulation configurations (e.g. to turn off complex subsystems) or to skip simulation after performing some actions. A consistent "run for record" may still be desirable under these circumstances.

**Comment by adrienmaillard** [comment]
In this ticket, I would also include pull simulation results from the database before scheduling. That would probably (provided that the user likes to look at his plan simulated) remove the first simulation the scheduler is doing to compute expressions.
