### ISSUE TITLE
Constraints: Express rolling window constraints in constraints eDSL

### ISSUE THREAD

**Issue by sloan-swieso** [NASA-AMMOS/aerie#689]
Copying https://jira.jpl.nasa.gov/browse/AERIEQS-396.

Currently there are 8 identified flight rules that rely on this type of check (and likely will be more).

> The use case is a flight rule that states a piece of hardware can only be powered on for 200 minutes across any given 8 hour span.
> 
> So the existing lessThan node could flag any occurrence when it is powered on for more than 200 minutes at once, but I also need to catch cases like if its powered on for 120 minutes, off for 60, and then back on for 120
> Reported by Sloan: https://jpl.slack.com/archives/C0163E42UBF/p1666903380420049

**Comment by joswig** [comment]
Several Flight Rules are blocked on this per discussion with @parkerabercrombie . Priority task for FY 23

**Comment by camargo** [comment]
This will be implemented in https://github.com/NASA-AMMOS/aerie/issues/830
