### ISSUE TITLE
Address invalid assumption in GetSimulationAction

### ISSUE THREAD

**Issue by mattdailis** [NASA-AMMOS/aerie#694]
As you can infer from its singular name, `GetSimulationAction` assumes that there is only one `simulation` record for a given plan. This is the line that makes that assumption:

https://github.com/NASA-AMMOS/aerie/blob/cd8f3460a2c6c8146d672ab9456f95be1bd2bcfa/merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/remotes/postgres/GetSimulationAction.java#L40

Our data model permits multiple simulation configurations for a plan - the goal of this ticket is to reconcile this discrepancy. This may involve having the `simulation_id` as an additional input to the `simulate` action. Perhaps it can be an optional input to allow backwards compatibility with the common case of one sim config per plan.

**Comment by Twisol** [comment]
> This may involve having the `simulation_id` as an additional input to the `simulate` action.

FWIW, every `simulation` entry is tied to a single plan, so if we take a `simulation_id`, we can either yeet the `plan_id` argument or just use it to validate the caller's assumptions (i.e. that this simulation is associated with this plan).

**Comment by camargo** [comment]
The database now enforces that there is only one `simulation` per plan
