### ISSUE TITLE
Support locals and parameters in the Sequencing EDSL

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#706]
The [Seq JSON spec](https://github.com/NASA-AMMOS/seq-json-schema/) supports passing sequence [parameters](https://github.com/NASA-AMMOS/seq-json-schema/blob/develop/schema.json#L651), and declaring [local variables](https://github.com/NASA-AMMOS/seq-json-schema/blob/develop/schema.json#L640). We need a way to allow declaring both parameters and locals in the sequencing EDSL, use them in the sequence, and properly output them in `.seq.json` as argument [symbols](https://github.com/NASA-AMMOS/seq-json-schema/blob/develop/schema.json#L392).

For example here is a proposed idea for how to do this in the EDSL. Psyche provided us one of their [sequence generation scripts](https://github.jpl.nasa.gov/PSYCHE/psyche-reusable-sequences/blob/develop/ep_swirl_preload.py), and [.seq.json output](https://github.jpl.nasa.gov/PSYCHE/psyche-reusable-sequences/blob/develop/ep/ep_swirl_preload/rs.ep_swirl_preload.r18.seq.json) we can draw inspiration from:

```ts
export default () =>
  Sequence.new({
    seqId: '',
    locals: [{ name: 'duration', type: 'FLOAT' }],
    parameters: [{ name: 'timeout', type: 'UINT' }],
    metadata: {},
    steps: [
      // Notice we use magic globals 'locals' and 'parameters' that bind to
      // the declared values in 'locals' and 'parameters' above.
      // This is just one idea.
      C.FSW_CMD_0({ arg0: locals.duration, arg1: parameters.timeout  })
    ],
  });
```

And the corresponding `.seq.json`:

```json
{
  "id": "",
  "metadata": {},
  "locals": [
    {
      "name": "duration",
      "type": "FLOAT"
    }
  ],
  "parameters": [
    {
      "name": "timeout",
      "type": "UINT"
    }
  ],
  "steps": [
    {
      "args": [
        { "name": "arg0", "type": "symbol", "value": "duration" },
        { "name": "arg1", "type": "symbol", "value": "timeout" }
      ],
      "stem": "FSW_CMD_0",
      "time": { "type": "COMMAND_COMPLETE" },
      "type": "command"
    }
  ]
}
```

**Comment by dyst5422** [comment]
We can do away with the array of objects and instead just use key value store with enum for the datatypes to be more ergonomic.

```ts
export default () =>
  Sequence.new({
    seqId: '',
    locals: { duration: DataTypes.Float },
    parameters: { timeout: DataTypes.Uint },
    metadata: {},
    steps: [
      // Notice we use magic globals 'locals' and 'parameters' that bind to
      // the declared values in 'locals' and 'parameters' above.
      // This is just one idea.
      C.FSW_CMD_0({ arg0: locals.duration, arg1: parameters.timeout  })
    ],
  });
```

I think perhaps we could even get tricky and find a way to do something like

```ts
export default () =>
  Sequence.new(({locals, parameters}) => ({
    seqId: '',
    metadata: {},
    steps: [
      // Notice we use magic globals 'locals' and 'parameters' that bind to
      // the declared values in 'locals' and 'parameters' above.
      // This is just one idea.
      C.FSW_CMD_0({ arg0: locals.duration, arg1: parameters.timeout  })
    ],
  }));
```

Though that might require a bit of AST level transforming.

I guess my initial reaction is that these are INPUTS and having them look and behave like INPUTS is a huge plus to ergonomics.

**Comment by camargo** [comment]
@dyst5422 For your second approach where are the passed `locals` and `parameters` defined?

**Comment by goetzrrGit** [comment]
Since we are following the JSON Spec we will need to export as`VariableDeclaration[]` https://github.com/NASA-AMMOS/seq-json-schema/blob/develop/types.ts#L8

**Comment by dyst5422** [comment]
> @dyst5422 For your second approach where are the passed `locals` and `parameters` defined?

I haven't gotten much time to think on it too much or play around with it, but my first instinct is to encode the types as type annotations on the locals and parameters and then pull them off using the AST the typescript compiler provides to encode in the SeqJson (the tricky part and perhaps prohibitively so)

So syntactically something like

```ts
export default () =>
  Sequence.new((inputs: {
    locals: { duration: DataTypes.Float },
    parameters: { timeout: DataTypes.Uint }
  }) => ({
    seqId: '',
    metadata: {},
    steps: [
      // Notice we use magic globals 'locals' and 'parameters' that bind to
      // the declared values in 'locals' and 'parameters' above.
      // This is just one idea.
      C.FSW_CMD_0({ arg0: inputs.locals.duration, arg1: inputs.parameters.timeout  })
    ],
  }));
```

This should give us typechecking on the locals and parameters in the editor. It's just a bit tricky to transform this into the SeqJSON.

An alternative signature for Sequence.new then looks something like

```ts
class Sequence {

  public new<
    Locals extends { [key: string]: DataType },
    Parameters extends { [key: string]: DataType },
  >(fn: (inputs: {
      locals: Locals,
      parameters: Parameters,
    }) => <Whatever our current new input type is, might have to add generics for locals and parameters that default to {}>)
}
```
And we would support the function signature for cases with inputs and the object signature for cases without.

**Comment by dyst5422** [comment]
A very similar API solution is possible.
```ts
export default () =>
  Sequence.new({
    seqId: '',
    locals: [{ name: 'duration', type: 'FLOAT' }],
    parameters: [{ name: 'timeout', type: 'UINT' }],
    metadata: {},
    steps: ({ locals, parameters}) => ([
      C.FSW_CMD_0({ arg0: locals.duration, arg1: parameters.timeout  })
    ]),
  });
```

See https://github.com/NASA-AMMOS/aerie/pull/856#issuecomment-1509202017
