### ISSUE TITLE
Simulation status is not dirty if sim config is changed

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#721]
If I simulate a plan and then change the simulation configuration, the sim status still shows as "green". In a past version I thought the status changed to "dirty" if the sim config changed. Now I need to change "simulation dataset ID" to "blank" in order to re-simulate the plan with the new configuration. Was this change intentional?

**Comment by camargo** [comment]
Closing, we are working on this in the UI, please follow: https://github.com/NASA-AMMOS/aerie-ui/issues/434
