### ISSUE TITLE
Need insight into status of the simulation engine

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#754]
nsims
https://jira.jpl.nasa.gov/browse/AERIEQS-453
Moderate
Administrators need to be able to gain insight in order to debug when a simulation fails, stalls, or is incomplete. Would be great if some of this information were accessible to users; but it is necessary for administrators.

Related to: https://jira.jpl.nasa.gov/browse/AERIEQS-433?filter=-2but is about access to status of simulation engine more broadly.

**Comment by joswig** [comment]
Simulation progress bar #771 addresses this
