### ISSUE TITLE
Update JNI SPICE library version

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#758]
anselr
https://jira.jpl.nasa.gov/browse/AERIEQS-441
Moderate
The Clipper Merlin mission model inherits its spice library from aerie, but there are certain features missing from the library since it is an old version (1.0 or something). To get the required spice functionality we would need to update to the most recent, which is 3.0.0. In particular, to address a need of the apgen to merlin transition the model needs access to the CSPICE::surfpv method for calculating surface intercept ground speed.

**Comment by parkerabercrombie** [comment]
@joswig recommend "moderate" priority.

**Comment by joswig** [comment]
preventing completion of the implementation of the geometry model resources from apgen
