### ISSUE TITLE
Sequences do not properly time-sort commands

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#759]
winner
https://jira.jpl.nasa.gov/browse/AERIEQS-440
Critical
Sequences do not appear to properly time-sort commands when overlapping activities are placed in the same sequence. See the example below. I would expect the following commands to be sorted and put in order based on their absolute time tags. This is a substantial and breaking issue for sequence generation.

**Comment by biqua** [comment]
@camargo please edit this issue ASAP to remove the expanded commands, thanks.

**Comment by camargo** [comment]
This is addressed with this milestone and associated issues: https://github.com/NASA-AMMOS/aerie/milestone/14
