### ISSUE TITLE
Need a way to stop a running simulation

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#765]
abercrom
https://jira.jpl.nasa.gov/browse/AERIEQS-451
Moderate
During thread test 2 we accidentally started a simulation with an incorrect configuration which caused the sim to to a very long time to run. We had to restart the worker container to get the sim to stop. Aerie needs a way for either the user or an administrator to stop a running simulation. (Restarting the container is a brute force solution, but application admins may not have permission to do that on production venues.)

**Comment by dandelany** [comment]
@Mythicaeda has implemented a way to stop simulation & has done some manual testing, is currently working on figuring out how to implement an automated test for this feature. Will need a bit of work on the UI side to hook up the "cancel" button & properly reflect cancelled run state for both the Simulation and for Scheduling. (scheduling cancellation probably deserves its own ticket).
