### ISSUE TITLE
Add model version to model selection dropdown menu

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#776]
anselr
https://jira.jpl.nasa.gov/browse/AERIEQS-376
Moderate
While creating a new plan, if there are multiple versions of a model with the same name they all appear identical in the dropdown menu when selecting a model. Having the version as a parenthetical would allow users to disambiguate models.

!image-2022-10-14-11-14-41-583.png!

**Comment by camargo** [comment]
Fixed in UI via https://github.com/NASA-AMMOS/aerie-ui/pull/819
