### ISSUE TITLE
Set activity instance metadata through a scheduling profile

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#777]
abercrom
https://jira.jpl.nasa.gov/browse/AERIEQS-373
Moderate
It would be useful to be able to set activity instance metadata through a scheduling profile, especially the activity instance name. This would allow a scheduling rule to assign a meaningful name to activity instances created by the scheduler.

**Comment by mattdailis** [comment]
Duplicate of #756
