### ISSUE TITLE
Expanded sequences missing required metadata

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#779]
nsims
https://jira.jpl.nasa.gov/browse/AERIEQS-368
Moderate
Missing 'onboard_path' and 'onboard_name' (required in Clipper SEQ JSONs, but not Aerie)

**Comment by camargo** [comment]
This should now be fixed since we support all of Seq JSON via https://github.com/NASA-AMMOS/aerie/issues/611
Please re-open if this is still an issue.
