### ISSUE TITLE
Invalid parameters error does not indicate solution

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#780]
nsims
https://jira.jpl.nasa.gov/browse/AERIEQS-361
Moderate
Error messages (like "activity parameters invalid") do not provide enough context to address

**Comment by camargo** [comment]
Closing since this should be partially handled by https://github.com/NASA-AMMOS/aerie-ui/pull/139
Additional updates will happen in https://github.com/NASA-AMMOS/aerie-ui/issues/281
