### ISSUE TITLE
Syntactic sugar for real resource range

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#785]
srschaff
https://jira.jpl.nasa.gov/browse/AERIEQS-335
Low
Within the typescript dsl, I would like to easily specify windows when a real resource is in a specific range. Currently that requires manually forming a conjunction of two separate queries. Unifying them will user typing (and typos!) but will also probably be a minor boost to evaluation performance.

For example something like
{quote}{{}}{{.applyWhen(}}

{{  Real.Resource("/solarAngle_deg").isBetween(10,30),}}

{{ )}}
{quote}
instead of currently this
{quote}{{}}{{{}.applyWhen(Windows.All({}}}{

{{  Real.Resource("/solarAngle_deg").greaterThan(10),}}

{{  Real.Resource("/solarAngle_deg").lessThan(30)}}

{{ ))}}
{quote}

**Comment by adrienmaillard** [comment]
this has been fixed by #1105 I believe
