### ISSUE TITLE
Revive the previously simulated state of a plan

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#786]
ramaswam
https://jira.jpl.nasa.gov/browse/AERIEQS-328
Medium
Planners can break a plan at a later stage during the process, and may want to revert back to a state where plan wasn't broken.

Aerie already captures all simulation data including plan inputs that seed the simulation.

It should be possible to revive an older state of the plan on a need basis. See Airtable snapshot revival workflow for reference.

This should meet the need to undo to some extent.

**Comment by camargo** [comment]
Closing as https://github.com/NASA-AMMOS/aerie/issues/884 will accomplish this
