### ISSUE TITLE
Display effect model of activity type in the UI

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#787]
ramaswam
https://jira.jpl.nasa.gov/browse/AERIEQS-327
Low
Planners can view implementation of an activity type via single click to understand its behavior.

One solution could be to link Aerie mission model to a github repo (of a specific branch or version), so that activity implementation can be linked.

**Comment by camargo** [comment]
Closing as out of scope. If we ever get another request for this we can create a new well-scoped ticket.
