### ISSUE TITLE
Replace "banana nation" with an example spacecraft

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#789]
abercrom
https://jira.jpl.nasa.gov/browse/AERIEQS-315
Moderate
Aerie documentation would be much more useful if it was based on an example spacecraft (could be a simple made-up mission) instead of "banana nation". Customers and stakeholders on Europa Clipper do not see how growing a banana relates to spacecraft planning. Having docs based on an example mission would allow us to share the info with our users and stakeholders without having to rewrite to put the information in mission context.

**Comment by camargo** [comment]
Closing this since we have future plans in our external mission model effort to provide multiple example mission models for many different types of spacecraft
