### ISSUE TITLE
Scheduler: Would like endsWithin clause to allow non-adjacent to anchor

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#791]
srschaff
https://jira.jpl.nasa.gov/browse/AERIEQS-311
Moderate
for example "endsWithin: TimingConstraint.range(WindowProperty.START, Operator.MINUS, 15 * 60 * 1000 * 1000)," will have it end anywhere from -15min to 0min before start of anchor

but sometimes want it to end anywhere from -15min to -5min before the start of the anchor. (for example a slew that needs some wait time after for pointing stability)

suggest allow specifying the full range, eg endsWithin(start.minus(-15),start.minus(-5))

**Comment by adrienmaillard** [comment]
This has been solved  by #1069
