### ISSUE TITLE
Can't add SEQ ID to activity before simulation

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#798]
winner
https://jira.jpl.nasa.gov/browse/AERIEQS-272
High
When adding a new activity to a plan, the ability to add a SEQ ID is shown but always fails before the simulation is run. This is mildly annoying on its own, since the Sequence ID box is available and selectable so from a UI perspective I would expect it to work, but it always fails. However, the big problem is when this happens to parent activities, because there is no SEQ ID available for children to inherit. Without the newly created children being able to pick up the parent's assigned sequence, it falls on the user to keep track of every new child activity that is spawned and manually assign it a sequence, which is both very annoying and a serious risk of missing a child when multiple new parent activities are added at once.

This is related to AERIEQS-273SEQ IDs are not inherited from parent activity and AERIEQS-274 Sequence IDs not persistent in a plan.

**Comment by biqua** [comment]
New issue links are #797 and #796 (to replace the AERIEQS references above.)

**Comment by joswig** [comment]
Plan to address #796 and #797 instead
