### ISSUE TITLE
Constraint Pattern: require activity A before next activity B

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#802]
ccamargo
https://jira.jpl.nasa.gov/browse/AERIEQS-212
Moderate
Some Clipper flight rules use language like "...before start of the next science observation". We already have a StartOf constraint node. To implement language like this we would like a "BeforeNext" constraint node.

Possible signature for this new constraint node:
 * *Return Type:*Set of windows
 * *Return Value:*All windows before the next window
 * *Required Fields:*
 ** {{expression}}: Expression yielding sets of windows
```[tasklist]
### Tasks
- [ ] https://github.com/NASA-AMMOS/aerie/issues/1112
- [ ] https://github.com/NASA-AMMOS/aerie/issues/1113
```

**Comment by mattdailis** [comment]
Both subtasks have been completed
