### ISSUE TITLE
Make constraint definition easily accessible from constraint violation 

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#804]
marijkej
https://jira.jpl.nasa.gov/browse/AERIEQS-204
Moderate
I would like to look at a constraint definition from the violation, since there will likely be 100s of constraints and you may not know the rules of all of them. Include thinking on quick view as well as deep link to edit. -Deb

**Comment by camargo** [comment]
This is resolved via https://github.com/NASA-AMMOS/aerie-ui/pull/847
