### ISSUE TITLE
Conversion scripts for backwards compatibility of SeqJSON files created prior to version 1.0.17

### ISSUE THREAD

**Issue by nat-sims** [NASA-AMMOS/aerie#810]
SeqJSON files made with the Sequence Editor prior to the schema changes cannot be uploaded. Would it be possible to get scripts to support backwards compatibility during this time of flux?

Related to: https://github.com/NASA-AMMOS/aerie/issues/738

**Comment by camargo** [comment]
Unfortunately we do not have the resources for this. That said the changes are not too drastic so quickly updating old `.seq.json` files should not be too difficult. I suspect Clipper could write their own script for this.
