### ISSUE TITLE
Pre-populate required arg keys when entering a command

### ISSUE THREAD

**Issue by nat-sims** [NASA-AMMOS/aerie#813]
Is it possible to auto-populate required arg keys, in the correct order, in the EDSL when entering a command? If there is a known fixed order, why make users choose?

The hinting and code completion is useful for simple commands, but when commands have several required parameters the hinting window truncates (i.e. "... and 4 more...") so users cannot see all that are required. This would also alleviate some of the extra work required to explicitly express every argument by name and value (a user concern).

Related to:
Control + space not working: https://github.com/NASA-AMMOS/aerie/issues/812
&
Arg hints not in correct order: https://github.com/NASA-AMMOS/aerie/issues/719

**Comment by camargo** [comment]
Closing in favor of https://github.com/NASA-AMMOS/aerie-ui/issues/570
