### ISSUE TITLE
SeqJSON allows 00:00:60 as a time tag, but fails in SEQGEN

### ISSUE THREAD

**Issue by nat-sims** [NASA-AMMOS/aerie#814]
Should be 00:01:00

**Comment by cartermak** [comment]
I believe [this documentation](https://tc39.es/proposal-temporal/docs/balancing.html) for the `Temporal` time library may explain why `"00:00:60"` is allowed in the EDSL and gets passed directly through to SEQGEN. Command generation should enforce balanced durations and check that output time strings (including durations > 1 day) are provided in the correct format.

**Comment by camargo** [comment]
Let's ask Taifun about this on the SeqGen side
