### ISSUE TITLE
Time order commands in expanded sequences

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#828]
When running command expansion where **multiple** activities target a **single** sequence, we need to time-order sort commands for that sequence. Currently we do no time ordering for any expanded sequences. Clipper wants time ordered commands in this special case. 

We only time order commands if **all** the commands in the target sequence have relative or absolute time. We will not time order the sequence if it contains complete or epoch-relative commands (even if it only has one).

**Comment by dyst5422** [comment]
Just a reminder that we put in the necessary extension functionality for this already and just haven't built it out deferring to figure out how we would handle mission specific configuration like this.

https://github.com/NASA-AMMOS/aerie/blob/develop/sequencing-server/src/defaultSeqBuilder.ts
