### ISSUE TITLE
Enable non-command step types in Command Expansion

### ISSUE THREAD

**Issue by cartermak** [NASA-AMMOS/aerie#853]
Currently, `Arrayable<CommandStem>` is the only allowable return value for command expansion. It will be necessary to activate/load/execute sequences via command expansion, so the `ExpansionReturn` type should allow these step types (which, I believe, are already added/being added to the EDSL).

**Comment by joswig** [comment]
Required for background sequence generation

**Comment by cartermak** [comment]
This is also required for some of our command expansions. Hopefully, it's a relatively simple change to the expansion return type since #926 is complete.
