### ISSUE TITLE
Add extended metadata fields to database

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#854]
Mission Model: Owner, Date Created, description
Plan: Date Created, Date Updated, Last Updated By, Owner
Simulation Dataset: Owner, Date Created
Expansion Rules: Owner, Date Created, Date Updated, Last Updated By, Description, Subsystem, Category
Expansion Sets: Name, Owner, Date Created, Date Updated, Last Updated By, Description, Subsystem
Sequences: Authored by, Date Created, Date Updated, Version, Subsystem
Constraints: Owner, Date Created, Date Updated, Last Updated By, Description, Subsystem, Category
Scheduling Goals: Owner, Date Created, Description, Subsystem, Category
Scheduling Requests: Scheduler

**Comment by camargo** [comment]
Also https://github.com/NASA-AMMOS/aerie/issues/795

**Comment by Mythicaeda** [comment]
Question regarding the "owner" field on these tables: are there any tables where there isn't one owner per item (ie plan, scheduling goal)?
