### ISSUE TITLE
Fix GraphQL Schema Issue

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#857]
We currently track the `scheduling_analysis` table in Hasura. Because this table only has one autogenerated column, the input object Hasura generates has an invalid schema [according to the GraphQL specification](https://spec.graphql.org/October2021/#sel-EAHhBXEBAAAEDFA5FoO).

Solutions:
- Add metadata to `scheduling_analysis`
- Don't track `scheduling_analysis` in Hasura
- Inline `scheduling_analysis` into `scheduling_request`

**Comment by mattdailis** [comment]
To make it easier to assess the completion of this ticket - could we please include a set of steps to reproduce (or maybe a better word is "observe") the problem?

**Comment by Mythicaeda** [comment]
A consistent way to make the error appear is to first place a valid query in our GraphiQL console, ie:

```graphql
query FinishedSimulations{
  simulation_dataset(where: {_and: {canceled: {_eq: false}, status: {_eq: "success"}}}) {
    id
    dataset_id
    arguments
    canceled
  }
}
```

Then click the "Derive Action" button along the top of the GraphiQL window. A banner will appear with the error.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/62574120/231587645-97a3b04d-3f92-48de-99be-6afe1c36ad4a.png">

**Comment by Twisol** [comment]
This seems like something that we might want to report upstream to Hasura, as well. Do we know if a similar issue has been reported yet?

**Comment by Mythicaeda** [comment]
~~Not that I can find.~~

Update: I've found [this issue](https://github.com/hasura/graphql-engine/issues/6528) in Hasura.
