### ISSUE TITLE
Provide more insight into scheduling failures

### ISSUE THREAD

**Issue by anselrd** [NASA-AMMOS/aerie#868]
When authoring a scheduling rule it would be helpful to provide some kind of resource that can hint to the cause of an activity not being scheduled. Some information that may help
* the ordered list of times that the scheduler tried to place the activity 
  * could also provide the failure mode, e.g. sim threw an error, did not meet startsAt/endsAt timing, activity was unfinished
* the exit condition of the scheduler, e.g. if the root finding method hit a maximum number of iterations or some error was generated by the scheduler

This information could be displayed to the UI or a log file, it doesn't really matter.

**Comment by adrienmaillard** [comment]
Closing this issue after merging #1188

**Comment by adrienmaillard** [comment]
Closing this issue after merging #1188
