### ISSUE TITLE
Make sure constraint names are unique

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#882]
Currently constraint names do not need to be unique. This can cause multiple violations to have the same name (violations do not point to a constraint via ID). We also throw an error when checking constraints if two constraints have the same name. This task is to just add a uniqueness constraint to the `name` column of the `constraint` table.

Additionally we should discuss and remove model constraints. See https://github.com/NASA-AMMOS/aerie/issues/892

**Comment by joswig** [comment]
Clipper would like to use the Flight Rule names for constraints, so we don't want to enforce global uniqueness, but should be differentiable within a plan context
