### ISSUE TITLE
Plan snapshots

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#884]
Expose a way to take a plan snapshot (separate from plans themselves). Snapshots should include all data associated with a plan. 
We also need a way to restore a plan from any of it's snapshots.
This will need a UI ticket we can make later.

### MVP

1. Allow taking a snapshot of activity directives
1. Allow setting a snapshot name, time snapshot was taken, and who took the snapshot
    - How do we tell the difference between snapshots taken by user vs automatic (plan merge) 
    - Will only show snapshots taken by users directly in UI
1. Exclude constraints, and goals for now

**Comment by joswig** [comment]
The google docs version naming is straightforward and effective

![Screenshot 2023-04-27 at 9 56 53 AM](https://user-images.githubusercontent.com/5984211/234935451-d340a241-7446-43e5-81e5-bad8981bb4dd.png)
