### ISSUE TITLE
Remove ability to associate constraint with a model

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#892]
Constraints only need to be associated with a plan. This is so constraints do not inadvertently change out from under a plan.

@JoelCourtney Notes we should have a nice way to copy constraints first otherwise this could be tedious. Imagine needing a set of 100 constraints for a new plan and needing to copy them over.

Related to https://github.com/NASA-AMMOS/aerie/issues/882

**Comment by mattdailis** [comment]
@parkerabercrombie notes that for their current use case, they exclusively use model constraints

**Comment by joswig** [comment]
it is useful to have constraints tied to a model, lets discuss before scheduling
