### ISSUE TITLE
Add Hasura metadata environment variables 

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#903]
- [actions.yml](https://github.com/NASA-AMMOS/aerie/blob/develop/deployment/hasura/metadata/actions.yaml) needs env variables for base URLs (e.g. `http://aerie_merlin:27183`) and timeouts
- [public_mission_model.yaml](https://github.com/NASA-AMMOS/aerie/blob/develop/deployment/hasura/metadata/databases/AerieMerlin/tables/public_mission_model.yaml) needs env variables for the webhooks URLs

**Comment by achong1024** [comment]
To be more specific
For actions.yaml we need
- http://aerie_merlin:27183
- http://aerie_sequencing:27184
- http://aerie_scheduler:27185
- timeout: <env_variable_for_the_time_out>

for hasura/metadata/databases/AerieMerlin/tables/public_mission_model.yaml
we need
- http://aerie_merlin:27183

Thank you

**Comment by camargo** [comment]
Noting that timeout env vars are not supported by Hasura. Created https://github.com/hasura/graphql-engine/issues/9630 to track.
