### ISSUE TITLE
Add `iterative` option for scheduling goals

### ISSUE THREAD

**Issue by JoelCourtney** [NASA-AMMOS/aerie#913]
To avoid malformed goals that could cause infinite loops in the scheduler, the scheduler should not iterate on goals by default. Turn that behavior off, and reenable it under a flag in the eDSL.

**Comment by mattdailis** [comment]
An alternative to consider here would be to check, after placing an activity, that it matches the finder, and take some action if it doesn't (somewhere on the scale between removing that particular activity, and failing scheduling)

Do you foresee the proposed toggle having utility beyond this specific problem with malformed activityFinders?

**Comment by JoelCourtney** [comment]
That would be helpful for other reasons, but loops can still happen with proper finders and templates. For each activity A, place activity A at the same time.

**Comment by adrienmaillard** [comment]
This iterative behavior is removed by #1051.
