### ISSUE TITLE
Implement permission checking for hasura_functions

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#944]
As mentioned in the [original Hasura Permissions issue](#861) and in #940, due to restrictions on what permissions Hasura allows us to set, some deviations from the planned permissions were made. See #940 for the description of these deviations. This ticket is for resolving those discrepancies.

**Comment by camargo** [comment]
Is this something we need for the MVP?

**Comment by Mythicaeda** [comment]
If Scheduling Goals and Plan Branch/Merge having plan owner/collaborator-based permissions are considered needed for the MVP, then yes. Otherwise, no, as they have basic permissions, just not the desired filter.

**Comment by camargo** [comment]
Okay. Do you have a sense for how we can solve these issues?

**Comment by Mythicaeda** [comment]
For the Plan Branch/Merge functions, there is [this workaround](https://mnesarco.github.io/blog/2020/02/25/hasura-postgresql-function-as-mutation) that I mentioned in #940, although that would require us to save all runs of each of those functions.

For the cross-db requirements for Scheduling, not yet, aside from us using webhooks instead of JWTs, or including the plan ownership/collaboratorship information in the JWT but having the token have a very short lifespan, < 1 minute. That way we can say that it may take up to a minute for a new plan owner/collaborator to be able to add/update/delete scheduling goals or to lose their ability to do so. I'm not sure if there would be any performance concerns in the Gateway if we were to go with the short JWT option.
