### ISSUE TITLE
Activity directives disappear when running simulation after scheduling

### ISSUE THREAD

**Issue by meganmjones** [NASA-AMMOS/aerie#965]
### Checked for duplicates

No - I haven't checked

### Is this a regression?

No - This is a new bug

### Version

1.6.0

### Describe the bug

After running a complex scheduling goal consisting of multiple placements of activity types and simulating, some of the activity directives disappear from the plan UI view. After the scheduling run, all activity directives are placed in the plan as expected, however after simulating, some seemingly random selection disappear. The activity directives and simulated activities still show up in the tables below the plan even though they don't have matches in the timeline view.

This bug makes debugging scheduling goals very challenging as the only way to get start/end times of the activity instances is clicking on the types in the UI view or referencing the activity/simulated activities table (which has duration and start offset which is not intuitive to debug off of).

Attaching two screen recordings of this happening. In the first one, you can see all the activity directives placed pre-simulation, then after, all but two activity directives disappear. In the second video, you can see only one chunk of the placed activity instances in the plan UI. The blue bars up top show where the others should be, but are not. I scrolled through the simulated activities table too, finding all correct instances that however do not show up in the UI.

https://github.com/NASA-AMMOS/aerie/assets/40210944/b2081e44-9d67-4ad2-ae10-04dabfdb97ee

https://github.com/NASA-AMMOS/aerie/assets/40210944/ea50de1b-71ad-4e66-a86d-427118df44e5

Attached below are the console logs when running the goal in the second video shared:
![Screenshot 2023-06-01 at 4 41 08 PM](https://github.com/NASA-AMMOS/aerie/assets/40210944/63510ea8-c72c-4bac-afc2-bc91cc72fe94)
![Screenshot 2023-06-01 at 4 41 14 PM](https://github.com/NASA-AMMOS/aerie/assets/40210944/3f24dc16-edd3-4f1a-b510-0a94aa1cb06b)

### Reproduction

This can be attempted to be reproduced by testing a scheduling goal (or set of goals) that place sets of activity instances (in the cases I've seen it has been multiple coexistence goals hooked to a primary anchor activity). Run the scheduler first and ensure all activity directives show up and then simulate and check again. In my case, the activity types always showed up in the activity directives/simulated activities table, yet some random assortment would not appear in the UI plan view.

### System Info

```shell
Google Chrome browser, macOS Ventura 13.3.1
```

### Severity

Moderate

**Comment by Mythicaeda** [comment]
This bug was reproduced on 1.12.0. The activity appeared to vanish from the timeline with the UI reporting an infinite loop because the activity span has a `parentId` = its own id. Additionally, all of the child spans had a `parentId` of `null`

<img width="418" alt="image" src="https://github.com/NASA-AMMOS/aerie/assets/62574120/64e2af9b-a5b5-48b4-adcb-3d098e6e67d3">
