### ISSUE TITLE
Scheduler should log status and errors

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#969]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

It is very difficult to debug errors in scheduling rules.

### Describe the feature request

It would be really useful if the scheduler could provide logs of what it's doing and errors that occur that cause scheduling to fail. We've hit several cases where a scheduling rule will fail, and we've needed to connect a debugger to the scheduler to figure out why. It would be useful to know:
* When the scheduler starts a simulation
* Which rule it is evaluating
* If an error occurs, what is the error and when did it occur

**Comment by adrienmaillard** [comment]
Similar to #868
