### ISSUE TITLE
Define a goal type that instantiates one single activity

### ISSUE THREAD

**Issue by jmdelfa** [NASA-AMMOS/aerie#994]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Describe the feature request

I want to add the capability to express a goal that results in the instantiation of one single activity. 
The use should be able to add logic or temporal conditions to the goal such as indicating the specific interval at where the activity should be place (for example a direct to earth communication from the rover at the end of a sol)

**Comment by jmdelfa** [comment]
CoexistenceGoal can be used to place a goal within an interval determined by certain condition. It is therefore proposed to close the ticket:

```ts
export default () =>
  Goal.CoexistenceGoal({
    forEach: Real.Resource('/fruit').greaterThan(1.0),
    activityTemplate: interval =>
      ActivityTemplates.BiteBanana({
        biteSize: 1,
      }),
    startsWithin: TimingConstraint.range(WindowProperty.END, Operator.PLUS, Temporal.Duration.from( { minutes: 5 })),
  });
 ```

**Comment by mattdailis** [comment]
Before closing this ticket, let's do the following:
- [ ] Update the example to specify a specific time window in the `forEach` clause
- [ ] Update the aerie-docs with an example of a goal that places an activity at a specific time
- [ ] Come up with a syntactic sugar example - i.e. what would be the most direct way to express that the goal places an activity at a specific time - compare that to the existing syntax, and decide whether the existing syntax is acceptable

**Comment by jmdelfa** [comment]
Updated example to place a single activity at a time instant:

```
export default () => Goal.CoexistenceGoal({
  forEach: Windows.Value(true, Interval.At(Temporal.Instant.from("2021-01-01T05:00:00.000Z"))).assignGaps(false),
  activityTemplate: (span) => ActivityTemplates.PeelBanana({peelDirection: "fromStem"}),
  startsAt: TimingConstraint.singleton(WindowProperty.START)
})

```
I will proceed now to upload two additional tests in SchedulingIntegrationTests and update the documentation
