### ISSUE TITLE
Add model and problem Allen temporal relations

### ISSUE THREAD

**Issue by jmdelfa** [NASA-AMMOS/aerie#995]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Describe the feature request

Extend the expressiveness of Aerie to represent Allen temporal relations between pairs (timepoint, timepoint), (timepoint, time-interval) or (time-interval, time-interval). These constraints should be able to be applied to the model (e.g intrinsic constrains related to the spacecraft), or problem-dependent

**Comment by mattdailis** [comment]
Before closing this ticket, let's do the following:
- [ ] Update the example to specify a specific time window in the `forEach` clause
- [ ] Update the aerie-docs with an example of a goal that places an activity at a specific time
- [ ] Come up with a syntactic sugar example - i.e. what would be the most direct way to express that the goal places an activity at a specific time - compare that to the existing syntax, and decide whether the existing syntax is acceptable
