### ISSUE TITLE
Store constraint violations

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#997]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Currently Aerie does not persist the result of a constraint check, the constraints can only be checked on-demand. For a mission that uses constraints to enforce flight rule checks (e.g. Europa Clipper) the constraint check result be should recorded so that operators can refer back to it, and so that mission tools can query for the constraint check data to include in reports. Without a persistent record there is no way to reliably recreate the run-for-record flight rule check in the case that a constraint definition is modified. For something as fundamental to mission safety as flight rule checks, I don't think we can rely on process alone to prevent changes to the constraint definitions, the result of the constraint check should be recorded.

### Describe the feature request

I want Aerie to record constraint checks in the database. I want to be able to query the API for all constraint checks for a given simulation dataset and constraint run, and get back all constraints that were checked (including those with no violations) and all violations found (including the window of time the constraint was in violation).

**Comment by camargo** [comment]
Related to https://github.com/NASA-AMMOS/aerie/issues/637
